package require -exact qsys 12.1
set_validation_property AUTOMATIC_VALIDATION false

add_instance single_kernel_system single_kernel_system

add_connection acl_iface.kernel_clk single_kernel_system.clock_reset
add_connection acl_iface.kernel_clk2x single_kernel_system.clock_reset2x
add_connection acl_iface.kernel_reset single_kernel_system.clock_reset_reset

add_connection single_kernel_system.avm_memgmem0_port_0_0_rw acl_iface.kernel_mem0
add_connection single_kernel_system.avm_memgmem0_port_1_0_rw acl_iface.kernel_mem1
add_connection acl_iface.kernel_irq single_kernel_system.kernel_irq

add_instance cra_root cra_ring_root
set_instance_parameter_value cra_root DATA_W 64
set_instance_parameter_value cra_root ADDR_W 5
set_instance_parameter_value cra_root ID_W 0
add_connection acl_iface.kernel_clk cra_root.clock
add_connection acl_iface.kernel_reset cra_root.reset
add_connection acl_iface.kernel_cra cra_root.cra_slave
set_connection_parameter_value acl_iface.kernel_cra/cra_root.cra_slave baseAddress "0x0"
add_instance avs_genetic_algorithm_cra_cra_ring cra_ring_node
set_instance_parameter_value avs_genetic_algorithm_cra_cra_ring DATA_W 64
set_instance_parameter_value avs_genetic_algorithm_cra_cra_ring RING_ADDR_W 5
set_instance_parameter_value avs_genetic_algorithm_cra_cra_ring CRA_ADDR_W 5
set_instance_parameter_value avs_genetic_algorithm_cra_cra_ring ID_W 0
set_instance_parameter_value avs_genetic_algorithm_cra_cra_ring ID 0
add_connection acl_iface.kernel_clk avs_genetic_algorithm_cra_cra_ring.clock
add_connection acl_iface.kernel_reset avs_genetic_algorithm_cra_cra_ring.reset
add_connection cra_root.ring_out avs_genetic_algorithm_cra_cra_ring.ring_in
add_connection avs_genetic_algorithm_cra_cra_ring.cra_master single_kernel_system.avs_genetic_algorithm_cra
set_connection_parameter_value avs_genetic_algorithm_cra_cra_ring.cra_master/single_kernel_system.avs_genetic_algorithm_cra baseAddress "0x0"
add_connection avs_genetic_algorithm_cra_cra_ring.ring_out cra_root.ring_in


save_system
