// system_acl_iface_mm_interconnect_9.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module system_acl_iface_mm_interconnect_9 (
		input  wire         pcie_coreclkout_clk,                                          //                                        pcie_coreclkout.clk
		input  wire         clock_cross_dma_to_pcie_m0_reset_reset_bridge_in_reset_reset, // clock_cross_dma_to_pcie_m0_reset_reset_bridge_in_reset.reset
		input  wire         pcie_Txs_translator_reset_reset_bridge_in_reset_reset,        //        pcie_Txs_translator_reset_reset_bridge_in_reset.reset
		input  wire [19:0]  clock_cross_dma_to_pcie_m0_address,                           //                             clock_cross_dma_to_pcie_m0.address
		output wire         clock_cross_dma_to_pcie_m0_waitrequest,                       //                                                       .waitrequest
		input  wire [4:0]   clock_cross_dma_to_pcie_m0_burstcount,                        //                                                       .burstcount
		input  wire [63:0]  clock_cross_dma_to_pcie_m0_byteenable,                        //                                                       .byteenable
		input  wire         clock_cross_dma_to_pcie_m0_read,                              //                                                       .read
		output wire [511:0] clock_cross_dma_to_pcie_m0_readdata,                          //                                                       .readdata
		output wire         clock_cross_dma_to_pcie_m0_readdatavalid,                     //                                                       .readdatavalid
		input  wire         clock_cross_dma_to_pcie_m0_write,                             //                                                       .write
		input  wire [511:0] clock_cross_dma_to_pcie_m0_writedata,                         //                                                       .writedata
		input  wire         clock_cross_dma_to_pcie_m0_debugaccess,                       //                                                       .debugaccess
		output wire [19:0]  pcie_Txs_address,                                             //                                               pcie_Txs.address
		output wire         pcie_Txs_write,                                               //                                                       .write
		output wire         pcie_Txs_read,                                                //                                                       .read
		input  wire [127:0] pcie_Txs_readdata,                                            //                                                       .readdata
		output wire [127:0] pcie_Txs_writedata,                                           //                                                       .writedata
		output wire [5:0]   pcie_Txs_burstcount,                                          //                                                       .burstcount
		output wire [15:0]  pcie_Txs_byteenable,                                          //                                                       .byteenable
		input  wire         pcie_Txs_readdatavalid,                                       //                                                       .readdatavalid
		input  wire         pcie_Txs_waitrequest,                                         //                                                       .waitrequest
		output wire         pcie_Txs_chipselect                                           //                                                       .chipselect
	);

	wire          clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_waitrequest;   // clock_cross_dma_to_pcie_m0_agent:av_waitrequest -> clock_cross_dma_to_pcie_m0_translator:uav_waitrequest
	wire  [511:0] clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_readdata;      // clock_cross_dma_to_pcie_m0_agent:av_readdata -> clock_cross_dma_to_pcie_m0_translator:uav_readdata
	wire          clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_debugaccess;   // clock_cross_dma_to_pcie_m0_translator:uav_debugaccess -> clock_cross_dma_to_pcie_m0_agent:av_debugaccess
	wire   [19:0] clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_address;       // clock_cross_dma_to_pcie_m0_translator:uav_address -> clock_cross_dma_to_pcie_m0_agent:av_address
	wire          clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_read;          // clock_cross_dma_to_pcie_m0_translator:uav_read -> clock_cross_dma_to_pcie_m0_agent:av_read
	wire   [63:0] clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_byteenable;    // clock_cross_dma_to_pcie_m0_translator:uav_byteenable -> clock_cross_dma_to_pcie_m0_agent:av_byteenable
	wire          clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_readdatavalid; // clock_cross_dma_to_pcie_m0_agent:av_readdatavalid -> clock_cross_dma_to_pcie_m0_translator:uav_readdatavalid
	wire          clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_lock;          // clock_cross_dma_to_pcie_m0_translator:uav_lock -> clock_cross_dma_to_pcie_m0_agent:av_lock
	wire          clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_write;         // clock_cross_dma_to_pcie_m0_translator:uav_write -> clock_cross_dma_to_pcie_m0_agent:av_write
	wire  [511:0] clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_writedata;     // clock_cross_dma_to_pcie_m0_translator:uav_writedata -> clock_cross_dma_to_pcie_m0_agent:av_writedata
	wire   [10:0] clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_burstcount;    // clock_cross_dma_to_pcie_m0_translator:uav_burstcount -> clock_cross_dma_to_pcie_m0_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                             // rsp_mux:src_valid -> clock_cross_dma_to_pcie_m0_agent:rp_valid
	wire  [637:0] rsp_mux_src_data;                                                              // rsp_mux:src_data -> clock_cross_dma_to_pcie_m0_agent:rp_data
	wire          rsp_mux_src_ready;                                                             // clock_cross_dma_to_pcie_m0_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                                           // rsp_mux:src_channel -> clock_cross_dma_to_pcie_m0_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                     // rsp_mux:src_startofpacket -> clock_cross_dma_to_pcie_m0_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                       // rsp_mux:src_endofpacket -> clock_cross_dma_to_pcie_m0_agent:rp_endofpacket
	wire  [127:0] pcie_txs_agent_m0_readdata;                                                    // pcie_Txs_translator:uav_readdata -> pcie_Txs_agent:m0_readdata
	wire          pcie_txs_agent_m0_waitrequest;                                                 // pcie_Txs_translator:uav_waitrequest -> pcie_Txs_agent:m0_waitrequest
	wire          pcie_txs_agent_m0_debugaccess;                                                 // pcie_Txs_agent:m0_debugaccess -> pcie_Txs_translator:uav_debugaccess
	wire   [19:0] pcie_txs_agent_m0_address;                                                     // pcie_Txs_agent:m0_address -> pcie_Txs_translator:uav_address
	wire   [15:0] pcie_txs_agent_m0_byteenable;                                                  // pcie_Txs_agent:m0_byteenable -> pcie_Txs_translator:uav_byteenable
	wire          pcie_txs_agent_m0_read;                                                        // pcie_Txs_agent:m0_read -> pcie_Txs_translator:uav_read
	wire          pcie_txs_agent_m0_readdatavalid;                                               // pcie_Txs_translator:uav_readdatavalid -> pcie_Txs_agent:m0_readdatavalid
	wire          pcie_txs_agent_m0_lock;                                                        // pcie_Txs_agent:m0_lock -> pcie_Txs_translator:uav_lock
	wire  [127:0] pcie_txs_agent_m0_writedata;                                                   // pcie_Txs_agent:m0_writedata -> pcie_Txs_translator:uav_writedata
	wire          pcie_txs_agent_m0_write;                                                       // pcie_Txs_agent:m0_write -> pcie_Txs_translator:uav_write
	wire    [9:0] pcie_txs_agent_m0_burstcount;                                                  // pcie_Txs_agent:m0_burstcount -> pcie_Txs_translator:uav_burstcount
	wire          pcie_txs_agent_rf_source_valid;                                                // pcie_Txs_agent:rf_source_valid -> pcie_Txs_agent_rsp_fifo:in_valid
	wire  [206:0] pcie_txs_agent_rf_source_data;                                                 // pcie_Txs_agent:rf_source_data -> pcie_Txs_agent_rsp_fifo:in_data
	wire          pcie_txs_agent_rf_source_ready;                                                // pcie_Txs_agent_rsp_fifo:in_ready -> pcie_Txs_agent:rf_source_ready
	wire          pcie_txs_agent_rf_source_startofpacket;                                        // pcie_Txs_agent:rf_source_startofpacket -> pcie_Txs_agent_rsp_fifo:in_startofpacket
	wire          pcie_txs_agent_rf_source_endofpacket;                                          // pcie_Txs_agent:rf_source_endofpacket -> pcie_Txs_agent_rsp_fifo:in_endofpacket
	wire          pcie_txs_agent_rsp_fifo_out_valid;                                             // pcie_Txs_agent_rsp_fifo:out_valid -> pcie_Txs_agent:rf_sink_valid
	wire  [206:0] pcie_txs_agent_rsp_fifo_out_data;                                              // pcie_Txs_agent_rsp_fifo:out_data -> pcie_Txs_agent:rf_sink_data
	wire          pcie_txs_agent_rsp_fifo_out_ready;                                             // pcie_Txs_agent:rf_sink_ready -> pcie_Txs_agent_rsp_fifo:out_ready
	wire          pcie_txs_agent_rsp_fifo_out_startofpacket;                                     // pcie_Txs_agent_rsp_fifo:out_startofpacket -> pcie_Txs_agent:rf_sink_startofpacket
	wire          pcie_txs_agent_rsp_fifo_out_endofpacket;                                       // pcie_Txs_agent_rsp_fifo:out_endofpacket -> pcie_Txs_agent:rf_sink_endofpacket
	wire          pcie_txs_agent_rdata_fifo_src_valid;                                           // pcie_Txs_agent:rdata_fifo_src_valid -> pcie_Txs_agent_rdata_fifo:in_valid
	wire  [129:0] pcie_txs_agent_rdata_fifo_src_data;                                            // pcie_Txs_agent:rdata_fifo_src_data -> pcie_Txs_agent_rdata_fifo:in_data
	wire          pcie_txs_agent_rdata_fifo_src_ready;                                           // pcie_Txs_agent_rdata_fifo:in_ready -> pcie_Txs_agent:rdata_fifo_src_ready
	wire          clock_cross_dma_to_pcie_m0_agent_cp_valid;                                     // clock_cross_dma_to_pcie_m0_agent:cp_valid -> router:sink_valid
	wire  [637:0] clock_cross_dma_to_pcie_m0_agent_cp_data;                                      // clock_cross_dma_to_pcie_m0_agent:cp_data -> router:sink_data
	wire          clock_cross_dma_to_pcie_m0_agent_cp_ready;                                     // router:sink_ready -> clock_cross_dma_to_pcie_m0_agent:cp_ready
	wire          clock_cross_dma_to_pcie_m0_agent_cp_startofpacket;                             // clock_cross_dma_to_pcie_m0_agent:cp_startofpacket -> router:sink_startofpacket
	wire          clock_cross_dma_to_pcie_m0_agent_cp_endofpacket;                               // clock_cross_dma_to_pcie_m0_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                              // router:src_valid -> cmd_demux:sink_valid
	wire  [637:0] router_src_data;                                                               // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                              // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                                            // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                      // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                        // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          pcie_txs_agent_rp_valid;                                                       // pcie_Txs_agent:rp_valid -> router_001:sink_valid
	wire  [205:0] pcie_txs_agent_rp_data;                                                        // pcie_Txs_agent:rp_data -> router_001:sink_data
	wire          pcie_txs_agent_rp_ready;                                                       // router_001:sink_ready -> pcie_Txs_agent:rp_ready
	wire          pcie_txs_agent_rp_startofpacket;                                               // pcie_Txs_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          pcie_txs_agent_rp_endofpacket;                                                 // pcie_Txs_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          pcie_txs_burst_adapter_source0_valid;                                          // pcie_Txs_burst_adapter:source0_valid -> pcie_Txs_agent:cp_valid
	wire  [205:0] pcie_txs_burst_adapter_source0_data;                                           // pcie_Txs_burst_adapter:source0_data -> pcie_Txs_agent:cp_data
	wire          pcie_txs_burst_adapter_source0_ready;                                          // pcie_Txs_agent:cp_ready -> pcie_Txs_burst_adapter:source0_ready
	wire    [0:0] pcie_txs_burst_adapter_source0_channel;                                        // pcie_Txs_burst_adapter:source0_channel -> pcie_Txs_agent:cp_channel
	wire          pcie_txs_burst_adapter_source0_startofpacket;                                  // pcie_Txs_burst_adapter:source0_startofpacket -> pcie_Txs_agent:cp_startofpacket
	wire          pcie_txs_burst_adapter_source0_endofpacket;                                    // pcie_Txs_burst_adapter:source0_endofpacket -> pcie_Txs_agent:cp_endofpacket
	wire          cmd_demux_src0_valid;                                                          // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [637:0] cmd_demux_src0_data;                                                           // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                          // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                                        // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                                  // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                    // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                          // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [637:0] rsp_demux_src0_data;                                                           // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                          // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                                        // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                                  // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                    // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          router_001_src_valid;                                                          // router_001:src_valid -> pcie_Txs_rsp_width_adapter:in_valid
	wire  [205:0] router_001_src_data;                                                           // router_001:src_data -> pcie_Txs_rsp_width_adapter:in_data
	wire          router_001_src_ready;                                                          // pcie_Txs_rsp_width_adapter:in_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                                        // router_001:src_channel -> pcie_Txs_rsp_width_adapter:in_channel
	wire          router_001_src_startofpacket;                                                  // router_001:src_startofpacket -> pcie_Txs_rsp_width_adapter:in_startofpacket
	wire          router_001_src_endofpacket;                                                    // router_001:src_endofpacket -> pcie_Txs_rsp_width_adapter:in_endofpacket
	wire          pcie_txs_rsp_width_adapter_src_valid;                                          // pcie_Txs_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire  [637:0] pcie_txs_rsp_width_adapter_src_data;                                           // pcie_Txs_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire          pcie_txs_rsp_width_adapter_src_ready;                                          // rsp_demux:sink_ready -> pcie_Txs_rsp_width_adapter:out_ready
	wire    [0:0] pcie_txs_rsp_width_adapter_src_channel;                                        // pcie_Txs_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire          pcie_txs_rsp_width_adapter_src_startofpacket;                                  // pcie_Txs_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire          pcie_txs_rsp_width_adapter_src_endofpacket;                                    // pcie_Txs_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_mux_src_valid;                                                             // cmd_mux:src_valid -> pcie_Txs_cmd_width_adapter:in_valid
	wire  [637:0] cmd_mux_src_data;                                                              // cmd_mux:src_data -> pcie_Txs_cmd_width_adapter:in_data
	wire          cmd_mux_src_ready;                                                             // pcie_Txs_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                                           // cmd_mux:src_channel -> pcie_Txs_cmd_width_adapter:in_channel
	wire          cmd_mux_src_startofpacket;                                                     // cmd_mux:src_startofpacket -> pcie_Txs_cmd_width_adapter:in_startofpacket
	wire          cmd_mux_src_endofpacket;                                                       // cmd_mux:src_endofpacket -> pcie_Txs_cmd_width_adapter:in_endofpacket
	wire          pcie_txs_cmd_width_adapter_src_valid;                                          // pcie_Txs_cmd_width_adapter:out_valid -> pcie_Txs_burst_adapter:sink0_valid
	wire  [205:0] pcie_txs_cmd_width_adapter_src_data;                                           // pcie_Txs_cmd_width_adapter:out_data -> pcie_Txs_burst_adapter:sink0_data
	wire          pcie_txs_cmd_width_adapter_src_ready;                                          // pcie_Txs_burst_adapter:sink0_ready -> pcie_Txs_cmd_width_adapter:out_ready
	wire    [0:0] pcie_txs_cmd_width_adapter_src_channel;                                        // pcie_Txs_cmd_width_adapter:out_channel -> pcie_Txs_burst_adapter:sink0_channel
	wire          pcie_txs_cmd_width_adapter_src_startofpacket;                                  // pcie_Txs_cmd_width_adapter:out_startofpacket -> pcie_Txs_burst_adapter:sink0_startofpacket
	wire          pcie_txs_cmd_width_adapter_src_endofpacket;                                    // pcie_Txs_cmd_width_adapter:out_endofpacket -> pcie_Txs_burst_adapter:sink0_endofpacket
	wire          pcie_txs_agent_rdata_fifo_out_valid;                                           // pcie_Txs_agent_rdata_fifo:out_valid -> avalon_st_adapter:in_0_valid
	wire  [129:0] pcie_txs_agent_rdata_fifo_out_data;                                            // pcie_Txs_agent_rdata_fifo:out_data -> avalon_st_adapter:in_0_data
	wire          pcie_txs_agent_rdata_fifo_out_ready;                                           // avalon_st_adapter:in_0_ready -> pcie_Txs_agent_rdata_fifo:out_ready
	wire          avalon_st_adapter_out_0_valid;                                                 // avalon_st_adapter:out_0_valid -> pcie_Txs_agent:rdata_fifo_sink_valid
	wire  [129:0] avalon_st_adapter_out_0_data;                                                  // avalon_st_adapter:out_0_data -> pcie_Txs_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                                 // pcie_Txs_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                                 // avalon_st_adapter:out_0_error -> pcie_Txs_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (20),
		.AV_DATA_W                   (512),
		.AV_BURSTCOUNT_W             (5),
		.AV_BYTEENABLE_W             (64),
		.UAV_ADDRESS_W               (20),
		.UAV_BURSTCOUNT_W            (11),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (64),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) clock_cross_dma_to_pcie_m0_translator (
		.clk                    (pcie_coreclkout_clk),                                                           //                       clk.clk
		.reset                  (clock_cross_dma_to_pcie_m0_reset_reset_bridge_in_reset_reset),                  //                     reset.reset
		.uav_address            (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (clock_cross_dma_to_pcie_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (clock_cross_dma_to_pcie_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (clock_cross_dma_to_pcie_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (clock_cross_dma_to_pcie_m0_byteenable),                                         //                          .byteenable
		.av_read                (clock_cross_dma_to_pcie_m0_read),                                               //                          .read
		.av_readdata            (clock_cross_dma_to_pcie_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (clock_cross_dma_to_pcie_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (clock_cross_dma_to_pcie_m0_write),                                              //                          .write
		.av_writedata           (clock_cross_dma_to_pcie_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (clock_cross_dma_to_pcie_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                                          //               (terminated)
		.av_begintransfer       (1'b0),                                                                          //               (terminated)
		.av_chipselect          (1'b0),                                                                          //               (terminated)
		.av_lock                (1'b0),                                                                          //               (terminated)
		.uav_clken              (),                                                                              //               (terminated)
		.av_clken               (1'b1),                                                                          //               (terminated)
		.uav_response           (2'b00),                                                                         //               (terminated)
		.av_response            (),                                                                              //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                          //               (terminated)
		.av_writeresponsevalid  ()                                                                               //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (20),
		.AV_DATA_W                      (128),
		.UAV_DATA_W                     (128),
		.AV_BURSTCOUNT_W                (6),
		.AV_BYTEENABLE_W                (16),
		.UAV_BYTEENABLE_W               (16),
		.UAV_ADDRESS_W                  (20),
		.UAV_BURSTCOUNT_W               (10),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (16),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (1),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) pcie_txs_translator (
		.clk                    (pcie_coreclkout_clk),                                   //                      clk.clk
		.reset                  (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (pcie_txs_agent_m0_address),                             // avalon_universal_slave_0.address
		.uav_burstcount         (pcie_txs_agent_m0_burstcount),                          //                         .burstcount
		.uav_read               (pcie_txs_agent_m0_read),                                //                         .read
		.uav_write              (pcie_txs_agent_m0_write),                               //                         .write
		.uav_waitrequest        (pcie_txs_agent_m0_waitrequest),                         //                         .waitrequest
		.uav_readdatavalid      (pcie_txs_agent_m0_readdatavalid),                       //                         .readdatavalid
		.uav_byteenable         (pcie_txs_agent_m0_byteenable),                          //                         .byteenable
		.uav_readdata           (pcie_txs_agent_m0_readdata),                            //                         .readdata
		.uav_writedata          (pcie_txs_agent_m0_writedata),                           //                         .writedata
		.uav_lock               (pcie_txs_agent_m0_lock),                                //                         .lock
		.uav_debugaccess        (pcie_txs_agent_m0_debugaccess),                         //                         .debugaccess
		.av_address             (pcie_Txs_address),                                      //      avalon_anti_slave_0.address
		.av_write               (pcie_Txs_write),                                        //                         .write
		.av_read                (pcie_Txs_read),                                         //                         .read
		.av_readdata            (pcie_Txs_readdata),                                     //                         .readdata
		.av_writedata           (pcie_Txs_writedata),                                    //                         .writedata
		.av_burstcount          (pcie_Txs_burstcount),                                   //                         .burstcount
		.av_byteenable          (pcie_Txs_byteenable),                                   //                         .byteenable
		.av_readdatavalid       (pcie_Txs_readdatavalid),                                //                         .readdatavalid
		.av_waitrequest         (pcie_Txs_waitrequest),                                  //                         .waitrequest
		.av_chipselect          (pcie_Txs_chipselect),                                   //                         .chipselect
		.av_begintransfer       (),                                                      //              (terminated)
		.av_beginbursttransfer  (),                                                      //              (terminated)
		.av_writebyteenable     (),                                                      //              (terminated)
		.av_lock                (),                                                      //              (terminated)
		.av_clken               (),                                                      //              (terminated)
		.uav_clken              (1'b0),                                                  //              (terminated)
		.av_debugaccess         (),                                                      //              (terminated)
		.av_outputenable        (),                                                      //              (terminated)
		.uav_response           (),                                                      //              (terminated)
		.av_response            (2'b00),                                                 //              (terminated)
		.uav_writeresponsevalid (),                                                      //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                   //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (637),
		.PKT_ORI_BURST_SIZE_L      (635),
		.PKT_RESPONSE_STATUS_H     (634),
		.PKT_RESPONSE_STATUS_L     (633),
		.PKT_QOS_H                 (622),
		.PKT_QOS_L                 (622),
		.PKT_DATA_SIDEBAND_H       (620),
		.PKT_DATA_SIDEBAND_L       (620),
		.PKT_ADDR_SIDEBAND_H       (619),
		.PKT_ADDR_SIDEBAND_L       (619),
		.PKT_BURST_TYPE_H          (618),
		.PKT_BURST_TYPE_L          (617),
		.PKT_CACHE_H               (632),
		.PKT_CACHE_L               (629),
		.PKT_THREAD_ID_H           (625),
		.PKT_THREAD_ID_L           (625),
		.PKT_BURST_SIZE_H          (616),
		.PKT_BURST_SIZE_L          (614),
		.PKT_TRANS_EXCLUSIVE       (601),
		.PKT_TRANS_LOCK            (600),
		.PKT_BEGIN_BURST           (621),
		.PKT_PROTECTION_H          (628),
		.PKT_PROTECTION_L          (626),
		.PKT_BURSTWRAP_H           (613),
		.PKT_BURSTWRAP_L           (613),
		.PKT_BYTE_CNT_H            (612),
		.PKT_BYTE_CNT_L            (602),
		.PKT_ADDR_H                (595),
		.PKT_ADDR_L                (576),
		.PKT_TRANS_COMPRESSED_READ (596),
		.PKT_TRANS_POSTED          (597),
		.PKT_TRANS_WRITE           (598),
		.PKT_TRANS_READ            (599),
		.PKT_DATA_H                (511),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (575),
		.PKT_BYTEEN_L              (512),
		.PKT_SRC_ID_H              (623),
		.PKT_SRC_ID_L              (623),
		.PKT_DEST_ID_H             (624),
		.PKT_DEST_ID_L             (624),
		.ST_DATA_W                 (638),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (11),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) clock_cross_dma_to_pcie_m0_agent (
		.clk                   (pcie_coreclkout_clk),                                                           //       clk.clk
		.reset                 (clock_cross_dma_to_pcie_m0_reset_reset_bridge_in_reset_reset),                  // clk_reset.reset
		.av_address            (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (clock_cross_dma_to_pcie_m0_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (clock_cross_dma_to_pcie_m0_agent_cp_valid),                                     //        cp.valid
		.cp_data               (clock_cross_dma_to_pcie_m0_agent_cp_data),                                      //          .data
		.cp_startofpacket      (clock_cross_dma_to_pcie_m0_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (clock_cross_dma_to_pcie_m0_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (clock_cross_dma_to_pcie_m0_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                             //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                              //          .data
		.rp_channel            (rsp_mux_src_channel),                                                           //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                     //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                       //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                             //          .ready
		.av_response           (),                                                                              // (terminated)
		.av_writeresponsevalid ()                                                                               // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (205),
		.PKT_ORI_BURST_SIZE_L      (203),
		.PKT_RESPONSE_STATUS_H     (202),
		.PKT_RESPONSE_STATUS_L     (201),
		.PKT_BURST_SIZE_H          (184),
		.PKT_BURST_SIZE_L          (182),
		.PKT_TRANS_LOCK            (168),
		.PKT_BEGIN_BURST           (189),
		.PKT_PROTECTION_H          (196),
		.PKT_PROTECTION_L          (194),
		.PKT_BURSTWRAP_H           (181),
		.PKT_BURSTWRAP_L           (181),
		.PKT_BYTE_CNT_H            (180),
		.PKT_BYTE_CNT_L            (170),
		.PKT_ADDR_H                (163),
		.PKT_ADDR_L                (144),
		.PKT_TRANS_COMPRESSED_READ (164),
		.PKT_TRANS_POSTED          (165),
		.PKT_TRANS_WRITE           (166),
		.PKT_TRANS_READ            (167),
		.PKT_DATA_H                (127),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_SRC_ID_H              (191),
		.PKT_SRC_ID_L              (191),
		.PKT_DEST_ID_H             (192),
		.PKT_DEST_ID_L             (192),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (206),
		.AVS_BURSTCOUNT_W          (10),
		.SUPPRESS_0_BYTEEN_CMD     (1),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) pcie_txs_agent (
		.clk                     (pcie_coreclkout_clk),                                   //             clk.clk
		.reset                   (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (pcie_txs_agent_m0_address),                             //              m0.address
		.m0_burstcount           (pcie_txs_agent_m0_burstcount),                          //                .burstcount
		.m0_byteenable           (pcie_txs_agent_m0_byteenable),                          //                .byteenable
		.m0_debugaccess          (pcie_txs_agent_m0_debugaccess),                         //                .debugaccess
		.m0_lock                 (pcie_txs_agent_m0_lock),                                //                .lock
		.m0_readdata             (pcie_txs_agent_m0_readdata),                            //                .readdata
		.m0_readdatavalid        (pcie_txs_agent_m0_readdatavalid),                       //                .readdatavalid
		.m0_read                 (pcie_txs_agent_m0_read),                                //                .read
		.m0_waitrequest          (pcie_txs_agent_m0_waitrequest),                         //                .waitrequest
		.m0_writedata            (pcie_txs_agent_m0_writedata),                           //                .writedata
		.m0_write                (pcie_txs_agent_m0_write),                               //                .write
		.rp_endofpacket          (pcie_txs_agent_rp_endofpacket),                         //              rp.endofpacket
		.rp_ready                (pcie_txs_agent_rp_ready),                               //                .ready
		.rp_valid                (pcie_txs_agent_rp_valid),                               //                .valid
		.rp_data                 (pcie_txs_agent_rp_data),                                //                .data
		.rp_startofpacket        (pcie_txs_agent_rp_startofpacket),                       //                .startofpacket
		.cp_ready                (pcie_txs_burst_adapter_source0_ready),                  //              cp.ready
		.cp_valid                (pcie_txs_burst_adapter_source0_valid),                  //                .valid
		.cp_data                 (pcie_txs_burst_adapter_source0_data),                   //                .data
		.cp_startofpacket        (pcie_txs_burst_adapter_source0_startofpacket),          //                .startofpacket
		.cp_endofpacket          (pcie_txs_burst_adapter_source0_endofpacket),            //                .endofpacket
		.cp_channel              (pcie_txs_burst_adapter_source0_channel),                //                .channel
		.rf_sink_ready           (pcie_txs_agent_rsp_fifo_out_ready),                     //         rf_sink.ready
		.rf_sink_valid           (pcie_txs_agent_rsp_fifo_out_valid),                     //                .valid
		.rf_sink_startofpacket   (pcie_txs_agent_rsp_fifo_out_startofpacket),             //                .startofpacket
		.rf_sink_endofpacket     (pcie_txs_agent_rsp_fifo_out_endofpacket),               //                .endofpacket
		.rf_sink_data            (pcie_txs_agent_rsp_fifo_out_data),                      //                .data
		.rf_source_ready         (pcie_txs_agent_rf_source_ready),                        //       rf_source.ready
		.rf_source_valid         (pcie_txs_agent_rf_source_valid),                        //                .valid
		.rf_source_startofpacket (pcie_txs_agent_rf_source_startofpacket),                //                .startofpacket
		.rf_source_endofpacket   (pcie_txs_agent_rf_source_endofpacket),                  //                .endofpacket
		.rf_source_data          (pcie_txs_agent_rf_source_data),                         //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                         // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                         //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                          //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                         //                .error
		.rdata_fifo_src_ready    (pcie_txs_agent_rdata_fifo_src_ready),                   //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (pcie_txs_agent_rdata_fifo_src_valid),                   //                .valid
		.rdata_fifo_src_data     (pcie_txs_agent_rdata_fifo_src_data),                    //                .data
		.m0_response             (2'b00),                                                 //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                   //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (207),
		.FIFO_DEPTH          (9),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) pcie_txs_agent_rsp_fifo (
		.clk               (pcie_coreclkout_clk),                                   //       clk.clk
		.reset             (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (pcie_txs_agent_rf_source_data),                         //        in.data
		.in_valid          (pcie_txs_agent_rf_source_valid),                        //          .valid
		.in_ready          (pcie_txs_agent_rf_source_ready),                        //          .ready
		.in_startofpacket  (pcie_txs_agent_rf_source_startofpacket),                //          .startofpacket
		.in_endofpacket    (pcie_txs_agent_rf_source_endofpacket),                  //          .endofpacket
		.out_data          (pcie_txs_agent_rsp_fifo_out_data),                      //       out.data
		.out_valid         (pcie_txs_agent_rsp_fifo_out_valid),                     //          .valid
		.out_ready         (pcie_txs_agent_rsp_fifo_out_ready),                     //          .ready
		.out_startofpacket (pcie_txs_agent_rsp_fifo_out_startofpacket),             //          .startofpacket
		.out_endofpacket   (pcie_txs_agent_rsp_fifo_out_endofpacket),               //          .endofpacket
		.csr_address       (2'b00),                                                 // (terminated)
		.csr_read          (1'b0),                                                  // (terminated)
		.csr_write         (1'b0),                                                  // (terminated)
		.csr_readdata      (),                                                      // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                  // (terminated)
		.almost_full_data  (),                                                      // (terminated)
		.almost_empty_data (),                                                      // (terminated)
		.in_empty          (1'b0),                                                  // (terminated)
		.out_empty         (),                                                      // (terminated)
		.in_error          (1'b0),                                                  // (terminated)
		.out_error         (),                                                      // (terminated)
		.in_channel        (1'b0),                                                  // (terminated)
		.out_channel       ()                                                       // (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (130),
		.FIFO_DEPTH          (16),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (3),
		.USE_MEMORY_BLOCKS   (1),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) pcie_txs_agent_rdata_fifo (
		.clk               (pcie_coreclkout_clk),                                   //       clk.clk
		.reset             (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (pcie_txs_agent_rdata_fifo_src_data),                    //        in.data
		.in_valid          (pcie_txs_agent_rdata_fifo_src_valid),                   //          .valid
		.in_ready          (pcie_txs_agent_rdata_fifo_src_ready),                   //          .ready
		.out_data          (pcie_txs_agent_rdata_fifo_out_data),                    //       out.data
		.out_valid         (pcie_txs_agent_rdata_fifo_out_valid),                   //          .valid
		.out_ready         (pcie_txs_agent_rdata_fifo_out_ready),                   //          .ready
		.csr_address       (2'b00),                                                 // (terminated)
		.csr_read          (1'b0),                                                  // (terminated)
		.csr_write         (1'b0),                                                  // (terminated)
		.csr_readdata      (),                                                      // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                  // (terminated)
		.almost_full_data  (),                                                      // (terminated)
		.almost_empty_data (),                                                      // (terminated)
		.in_startofpacket  (1'b0),                                                  // (terminated)
		.in_endofpacket    (1'b0),                                                  // (terminated)
		.out_startofpacket (),                                                      // (terminated)
		.out_endofpacket   (),                                                      // (terminated)
		.in_empty          (1'b0),                                                  // (terminated)
		.out_empty         (),                                                      // (terminated)
		.in_error          (1'b0),                                                  // (terminated)
		.out_error         (),                                                      // (terminated)
		.in_channel        (1'b0),                                                  // (terminated)
		.out_channel       ()                                                       // (terminated)
	);

	system_acl_iface_mm_interconnect_9_router router (
		.sink_ready         (clock_cross_dma_to_pcie_m0_agent_cp_ready),                    //      sink.ready
		.sink_valid         (clock_cross_dma_to_pcie_m0_agent_cp_valid),                    //          .valid
		.sink_data          (clock_cross_dma_to_pcie_m0_agent_cp_data),                     //          .data
		.sink_startofpacket (clock_cross_dma_to_pcie_m0_agent_cp_startofpacket),            //          .startofpacket
		.sink_endofpacket   (clock_cross_dma_to_pcie_m0_agent_cp_endofpacket),              //          .endofpacket
		.clk                (pcie_coreclkout_clk),                                          //       clk.clk
		.reset              (clock_cross_dma_to_pcie_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                             //       src.ready
		.src_valid          (router_src_valid),                                             //          .valid
		.src_data           (router_src_data),                                              //          .data
		.src_channel        (router_src_channel),                                           //          .channel
		.src_startofpacket  (router_src_startofpacket),                                     //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                        //          .endofpacket
	);

	system_acl_iface_mm_interconnect_9_router_001 router_001 (
		.sink_ready         (pcie_txs_agent_rp_ready),                               //      sink.ready
		.sink_valid         (pcie_txs_agent_rp_valid),                               //          .valid
		.sink_data          (pcie_txs_agent_rp_data),                                //          .data
		.sink_startofpacket (pcie_txs_agent_rp_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (pcie_txs_agent_rp_endofpacket),                         //          .endofpacket
		.clk                (pcie_coreclkout_clk),                                   //       clk.clk
		.reset              (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                  //       src.ready
		.src_valid          (router_001_src_valid),                                  //          .valid
		.src_data           (router_001_src_data),                                   //          .data
		.src_channel        (router_001_src_channel),                                //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                          //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                             //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (163),
		.PKT_ADDR_L                (144),
		.PKT_BEGIN_BURST           (189),
		.PKT_BYTE_CNT_H            (180),
		.PKT_BYTE_CNT_L            (170),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_BURST_SIZE_H          (184),
		.PKT_BURST_SIZE_L          (182),
		.PKT_BURST_TYPE_H          (186),
		.PKT_BURST_TYPE_L          (185),
		.PKT_BURSTWRAP_H           (181),
		.PKT_BURSTWRAP_L           (181),
		.PKT_TRANS_COMPRESSED_READ (164),
		.PKT_TRANS_WRITE           (166),
		.PKT_TRANS_READ            (167),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (206),
		.ST_CHANNEL_W              (1),
		.OUT_BYTE_CNT_H            (179),
		.OUT_BURSTWRAP_H           (181),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("13.1")
	) pcie_txs_burst_adapter (
		.clk                   (pcie_coreclkout_clk),                                   //       cr0.clk
		.reset                 (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.sink0_valid           (pcie_txs_cmd_width_adapter_src_valid),                  //     sink0.valid
		.sink0_data            (pcie_txs_cmd_width_adapter_src_data),                   //          .data
		.sink0_channel         (pcie_txs_cmd_width_adapter_src_channel),                //          .channel
		.sink0_startofpacket   (pcie_txs_cmd_width_adapter_src_startofpacket),          //          .startofpacket
		.sink0_endofpacket     (pcie_txs_cmd_width_adapter_src_endofpacket),            //          .endofpacket
		.sink0_ready           (pcie_txs_cmd_width_adapter_src_ready),                  //          .ready
		.source0_valid         (pcie_txs_burst_adapter_source0_valid),                  //   source0.valid
		.source0_data          (pcie_txs_burst_adapter_source0_data),                   //          .data
		.source0_channel       (pcie_txs_burst_adapter_source0_channel),                //          .channel
		.source0_startofpacket (pcie_txs_burst_adapter_source0_startofpacket),          //          .startofpacket
		.source0_endofpacket   (pcie_txs_burst_adapter_source0_endofpacket),            //          .endofpacket
		.source0_ready         (pcie_txs_burst_adapter_source0_ready)                   //          .ready
	);

	system_acl_iface_mm_interconnect_9_cmd_demux cmd_demux (
		.clk                (pcie_coreclkout_clk),                                          //       clk.clk
		.reset              (clock_cross_dma_to_pcie_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                             //      sink.ready
		.sink_channel       (router_src_channel),                                           //          .channel
		.sink_data          (router_src_data),                                              //          .data
		.sink_startofpacket (router_src_startofpacket),                                     //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                       //          .endofpacket
		.sink_valid         (router_src_valid),                                             //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                         //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                         //          .valid
		.src0_data          (cmd_demux_src0_data),                                          //          .data
		.src0_channel       (cmd_demux_src0_channel),                                       //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                 //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                    //          .endofpacket
	);

	system_acl_iface_mm_interconnect_9_cmd_mux cmd_mux (
		.clk                 (pcie_coreclkout_clk),                                   //       clk.clk
		.reset               (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                     //       src.ready
		.src_valid           (cmd_mux_src_valid),                                     //          .valid
		.src_data            (cmd_mux_src_data),                                      //          .data
		.src_channel         (cmd_mux_src_channel),                                   //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                             //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                               //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                  //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                  //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                                //          .channel
		.sink0_data          (cmd_demux_src0_data),                                   //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                          //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                             //          .endofpacket
	);

	system_acl_iface_mm_interconnect_9_cmd_demux rsp_demux (
		.clk                (pcie_coreclkout_clk),                                   //       clk.clk
		.reset              (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (pcie_txs_rsp_width_adapter_src_ready),                  //      sink.ready
		.sink_channel       (pcie_txs_rsp_width_adapter_src_channel),                //          .channel
		.sink_data          (pcie_txs_rsp_width_adapter_src_data),                   //          .data
		.sink_startofpacket (pcie_txs_rsp_width_adapter_src_startofpacket),          //          .startofpacket
		.sink_endofpacket   (pcie_txs_rsp_width_adapter_src_endofpacket),            //          .endofpacket
		.sink_valid         (pcie_txs_rsp_width_adapter_src_valid),                  //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                  //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                  //          .valid
		.src0_data          (rsp_demux_src0_data),                                   //          .data
		.src0_channel       (rsp_demux_src0_channel),                                //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                          //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                             //          .endofpacket
	);

	system_acl_iface_mm_interconnect_9_rsp_mux rsp_mux (
		.clk                 (pcie_coreclkout_clk),                                          //       clk.clk
		.reset               (clock_cross_dma_to_pcie_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                            //       src.ready
		.src_valid           (rsp_mux_src_valid),                                            //          .valid
		.src_data            (rsp_mux_src_data),                                             //          .data
		.src_channel         (rsp_mux_src_channel),                                          //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                    //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                      //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                         //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                         //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                       //          .channel
		.sink0_data          (rsp_demux_src0_data),                                          //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                                 //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                                    //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (163),
		.IN_PKT_ADDR_L                 (144),
		.IN_PKT_DATA_H                 (127),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (143),
		.IN_PKT_BYTEEN_L               (128),
		.IN_PKT_BYTE_CNT_H             (180),
		.IN_PKT_BYTE_CNT_L             (170),
		.IN_PKT_TRANS_COMPRESSED_READ  (164),
		.IN_PKT_TRANS_WRITE            (166),
		.IN_PKT_BURSTWRAP_H            (181),
		.IN_PKT_BURSTWRAP_L            (181),
		.IN_PKT_BURST_SIZE_H           (184),
		.IN_PKT_BURST_SIZE_L           (182),
		.IN_PKT_RESPONSE_STATUS_H      (202),
		.IN_PKT_RESPONSE_STATUS_L      (201),
		.IN_PKT_TRANS_EXCLUSIVE        (169),
		.IN_PKT_BURST_TYPE_H           (186),
		.IN_PKT_BURST_TYPE_L           (185),
		.IN_PKT_ORI_BURST_SIZE_L       (203),
		.IN_PKT_ORI_BURST_SIZE_H       (205),
		.IN_ST_DATA_W                  (206),
		.OUT_PKT_ADDR_H                (595),
		.OUT_PKT_ADDR_L                (576),
		.OUT_PKT_DATA_H                (511),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (575),
		.OUT_PKT_BYTEEN_L              (512),
		.OUT_PKT_BYTE_CNT_H            (612),
		.OUT_PKT_BYTE_CNT_L            (602),
		.OUT_PKT_TRANS_COMPRESSED_READ (596),
		.OUT_PKT_BURST_SIZE_H          (616),
		.OUT_PKT_BURST_SIZE_L          (614),
		.OUT_PKT_RESPONSE_STATUS_H     (634),
		.OUT_PKT_RESPONSE_STATUS_L     (633),
		.OUT_PKT_TRANS_EXCLUSIVE       (601),
		.OUT_PKT_BURST_TYPE_H          (618),
		.OUT_PKT_BURST_TYPE_L          (617),
		.OUT_PKT_ORI_BURST_SIZE_L      (635),
		.OUT_PKT_ORI_BURST_SIZE_H      (637),
		.OUT_ST_DATA_W                 (638),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) pcie_txs_rsp_width_adapter (
		.clk                  (pcie_coreclkout_clk),                                   //       clk.clk
		.reset                (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (router_001_src_valid),                                  //      sink.valid
		.in_channel           (router_001_src_channel),                                //          .channel
		.in_startofpacket     (router_001_src_startofpacket),                          //          .startofpacket
		.in_endofpacket       (router_001_src_endofpacket),                            //          .endofpacket
		.in_ready             (router_001_src_ready),                                  //          .ready
		.in_data              (router_001_src_data),                                   //          .data
		.out_endofpacket      (pcie_txs_rsp_width_adapter_src_endofpacket),            //       src.endofpacket
		.out_data             (pcie_txs_rsp_width_adapter_src_data),                   //          .data
		.out_channel          (pcie_txs_rsp_width_adapter_src_channel),                //          .channel
		.out_valid            (pcie_txs_rsp_width_adapter_src_valid),                  //          .valid
		.out_ready            (pcie_txs_rsp_width_adapter_src_ready),                  //          .ready
		.out_startofpacket    (pcie_txs_rsp_width_adapter_src_startofpacket),          //          .startofpacket
		.in_command_size_data (3'b000)                                                 // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (595),
		.IN_PKT_ADDR_L                 (576),
		.IN_PKT_DATA_H                 (511),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (575),
		.IN_PKT_BYTEEN_L               (512),
		.IN_PKT_BYTE_CNT_H             (612),
		.IN_PKT_BYTE_CNT_L             (602),
		.IN_PKT_TRANS_COMPRESSED_READ  (596),
		.IN_PKT_TRANS_WRITE            (598),
		.IN_PKT_BURSTWRAP_H            (613),
		.IN_PKT_BURSTWRAP_L            (613),
		.IN_PKT_BURST_SIZE_H           (616),
		.IN_PKT_BURST_SIZE_L           (614),
		.IN_PKT_RESPONSE_STATUS_H      (634),
		.IN_PKT_RESPONSE_STATUS_L      (633),
		.IN_PKT_TRANS_EXCLUSIVE        (601),
		.IN_PKT_BURST_TYPE_H           (618),
		.IN_PKT_BURST_TYPE_L           (617),
		.IN_PKT_ORI_BURST_SIZE_L       (635),
		.IN_PKT_ORI_BURST_SIZE_H       (637),
		.IN_ST_DATA_W                  (638),
		.OUT_PKT_ADDR_H                (163),
		.OUT_PKT_ADDR_L                (144),
		.OUT_PKT_DATA_H                (127),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (143),
		.OUT_PKT_BYTEEN_L              (128),
		.OUT_PKT_BYTE_CNT_H            (180),
		.OUT_PKT_BYTE_CNT_L            (170),
		.OUT_PKT_TRANS_COMPRESSED_READ (164),
		.OUT_PKT_BURST_SIZE_H          (184),
		.OUT_PKT_BURST_SIZE_L          (182),
		.OUT_PKT_RESPONSE_STATUS_H     (202),
		.OUT_PKT_RESPONSE_STATUS_L     (201),
		.OUT_PKT_TRANS_EXCLUSIVE       (169),
		.OUT_PKT_BURST_TYPE_H          (186),
		.OUT_PKT_BURST_TYPE_L          (185),
		.OUT_PKT_ORI_BURST_SIZE_L      (203),
		.OUT_PKT_ORI_BURST_SIZE_H      (205),
		.OUT_ST_DATA_W                 (206),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) pcie_txs_cmd_width_adapter (
		.clk                  (pcie_coreclkout_clk),                                   //       clk.clk
		.reset                (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                                     //      sink.valid
		.in_channel           (cmd_mux_src_channel),                                   //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                             //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                               //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                                     //          .ready
		.in_data              (cmd_mux_src_data),                                      //          .data
		.out_endofpacket      (pcie_txs_cmd_width_adapter_src_endofpacket),            //       src.endofpacket
		.out_data             (pcie_txs_cmd_width_adapter_src_data),                   //          .data
		.out_channel          (pcie_txs_cmd_width_adapter_src_channel),                //          .channel
		.out_valid            (pcie_txs_cmd_width_adapter_src_valid),                  //          .valid
		.out_ready            (pcie_txs_cmd_width_adapter_src_ready),                  //          .ready
		.out_startofpacket    (pcie_txs_cmd_width_adapter_src_startofpacket),          //          .startofpacket
		.in_command_size_data (3'b000)                                                 // (terminated)
	);

	system_acl_iface_mm_interconnect_9_avalon_st_adapter #(
		.inBitsPerSymbol (130),
		.inUsePackets    (0),
		.inDataWidth     (130),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (130),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (pcie_coreclkout_clk),                                   // in_clk_0.clk
		.in_rst_0_reset (pcie_Txs_translator_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (pcie_txs_agent_rdata_fifo_out_data),                    //     in_0.data
		.in_0_valid     (pcie_txs_agent_rdata_fifo_out_valid),                   //         .valid
		.in_0_ready     (pcie_txs_agent_rdata_fifo_out_ready),                   //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                          //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                         //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                         //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                          //         .error
	);

endmodule
