// system_acl_iface_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module system_acl_iface_mm_interconnect_0 (
		input  wire         ddr3a_afi_clk_clk,                                       //                                     ddr3a_afi_clk.clk
		input  wire         ddr3a_avl_translator_reset_reset_bridge_in_reset_reset,  //  ddr3a_avl_translator_reset_reset_bridge_in_reset.reset
		input  wire         ddr3a_soft_reset_reset_bridge_in_reset_reset,            //            ddr3a_soft_reset_reset_bridge_in_reset.reset
		input  wire         pipe_stage_ddr3a_dimm_reset_reset_bridge_in_reset_reset, // pipe_stage_ddr3a_dimm_reset_reset_bridge_in_reset.reset
		input  wire [30:0]  pipe_stage_ddr3a_dimm_m0_address,                        //                          pipe_stage_ddr3a_dimm_m0.address
		output wire         pipe_stage_ddr3a_dimm_m0_waitrequest,                    //                                                  .waitrequest
		input  wire [4:0]   pipe_stage_ddr3a_dimm_m0_burstcount,                     //                                                  .burstcount
		input  wire [63:0]  pipe_stage_ddr3a_dimm_m0_byteenable,                     //                                                  .byteenable
		input  wire         pipe_stage_ddr3a_dimm_m0_read,                           //                                                  .read
		output wire [511:0] pipe_stage_ddr3a_dimm_m0_readdata,                       //                                                  .readdata
		output wire         pipe_stage_ddr3a_dimm_m0_readdatavalid,                  //                                                  .readdatavalid
		input  wire         pipe_stage_ddr3a_dimm_m0_write,                          //                                                  .write
		input  wire [511:0] pipe_stage_ddr3a_dimm_m0_writedata,                      //                                                  .writedata
		input  wire         pipe_stage_ddr3a_dimm_m0_debugaccess,                    //                                                  .debugaccess
		output wire [24:0]  ddr3a_avl_address,                                       //                                         ddr3a_avl.address
		output wire         ddr3a_avl_write,                                         //                                                  .write
		output wire         ddr3a_avl_read,                                          //                                                  .read
		input  wire [511:0] ddr3a_avl_readdata,                                      //                                                  .readdata
		output wire [511:0] ddr3a_avl_writedata,                                     //                                                  .writedata
		output wire         ddr3a_avl_beginbursttransfer,                            //                                                  .beginbursttransfer
		output wire [4:0]   ddr3a_avl_burstcount,                                    //                                                  .burstcount
		output wire [63:0]  ddr3a_avl_byteenable,                                    //                                                  .byteenable
		input  wire         ddr3a_avl_readdatavalid,                                 //                                                  .readdatavalid
		input  wire         ddr3a_avl_waitrequest                                    //                                                  .waitrequest
	);

	wire          pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_waitrequest;   // ddr3a_avl_translator:uav_waitrequest -> pipe_stage_ddr3a_dimm_m0_translator:uav_waitrequest
	wire  [511:0] pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_readdata;      // ddr3a_avl_translator:uav_readdata -> pipe_stage_ddr3a_dimm_m0_translator:uav_readdata
	wire          pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_debugaccess;   // pipe_stage_ddr3a_dimm_m0_translator:uav_debugaccess -> ddr3a_avl_translator:uav_debugaccess
	wire   [30:0] pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_address;       // pipe_stage_ddr3a_dimm_m0_translator:uav_address -> ddr3a_avl_translator:uav_address
	wire          pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_read;          // pipe_stage_ddr3a_dimm_m0_translator:uav_read -> ddr3a_avl_translator:uav_read
	wire   [63:0] pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_byteenable;    // pipe_stage_ddr3a_dimm_m0_translator:uav_byteenable -> ddr3a_avl_translator:uav_byteenable
	wire          pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_readdatavalid; // ddr3a_avl_translator:uav_readdatavalid -> pipe_stage_ddr3a_dimm_m0_translator:uav_readdatavalid
	wire          pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_lock;          // pipe_stage_ddr3a_dimm_m0_translator:uav_lock -> ddr3a_avl_translator:uav_lock
	wire          pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_write;         // pipe_stage_ddr3a_dimm_m0_translator:uav_write -> ddr3a_avl_translator:uav_write
	wire  [511:0] pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_writedata;     // pipe_stage_ddr3a_dimm_m0_translator:uav_writedata -> ddr3a_avl_translator:uav_writedata
	wire   [10:0] pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_burstcount;    // pipe_stage_ddr3a_dimm_m0_translator:uav_burstcount -> ddr3a_avl_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (31),
		.AV_DATA_W                   (512),
		.AV_BURSTCOUNT_W             (5),
		.AV_BYTEENABLE_W             (64),
		.UAV_ADDRESS_W               (31),
		.UAV_BURSTCOUNT_W            (11),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (64),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) pipe_stage_ddr3a_dimm_m0_translator (
		.clk                    (ddr3a_afi_clk_clk),                                                           //                       clk.clk
		.reset                  (pipe_stage_ddr3a_dimm_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (pipe_stage_ddr3a_dimm_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (pipe_stage_ddr3a_dimm_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (pipe_stage_ddr3a_dimm_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (pipe_stage_ddr3a_dimm_m0_byteenable),                                         //                          .byteenable
		.av_read                (pipe_stage_ddr3a_dimm_m0_read),                                               //                          .read
		.av_readdata            (pipe_stage_ddr3a_dimm_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (pipe_stage_ddr3a_dimm_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (pipe_stage_ddr3a_dimm_m0_write),                                              //                          .write
		.av_writedata           (pipe_stage_ddr3a_dimm_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (pipe_stage_ddr3a_dimm_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                                        //               (terminated)
		.av_begintransfer       (1'b0),                                                                        //               (terminated)
		.av_chipselect          (1'b0),                                                                        //               (terminated)
		.av_lock                (1'b0),                                                                        //               (terminated)
		.uav_clken              (),                                                                            //               (terminated)
		.av_clken               (1'b1),                                                                        //               (terminated)
		.uav_response           (2'b00),                                                                       //               (terminated)
		.av_response            (),                                                                            //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                        //               (terminated)
		.av_writeresponsevalid  ()                                                                             //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (25),
		.AV_DATA_W                      (512),
		.UAV_DATA_W                     (512),
		.AV_BURSTCOUNT_W                (5),
		.AV_BYTEENABLE_W                (64),
		.UAV_BYTEENABLE_W               (64),
		.UAV_ADDRESS_W                  (31),
		.UAV_BURSTCOUNT_W               (11),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (64),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) ddr3a_avl_translator (
		.clk                    (ddr3a_afi_clk_clk),                                                           //                      clk.clk
		.reset                  (ddr3a_avl_translator_reset_reset_bridge_in_reset_reset),                      //                    reset.reset
		.uav_address            (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (pipe_stage_ddr3a_dimm_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (ddr3a_avl_address),                                                           //      avalon_anti_slave_0.address
		.av_write               (ddr3a_avl_write),                                                             //                         .write
		.av_read                (ddr3a_avl_read),                                                              //                         .read
		.av_readdata            (ddr3a_avl_readdata),                                                          //                         .readdata
		.av_writedata           (ddr3a_avl_writedata),                                                         //                         .writedata
		.av_beginbursttransfer  (ddr3a_avl_beginbursttransfer),                                                //                         .beginbursttransfer
		.av_burstcount          (ddr3a_avl_burstcount),                                                        //                         .burstcount
		.av_byteenable          (ddr3a_avl_byteenable),                                                        //                         .byteenable
		.av_readdatavalid       (ddr3a_avl_readdatavalid),                                                     //                         .readdatavalid
		.av_waitrequest         (ddr3a_avl_waitrequest),                                                       //                         .waitrequest
		.av_begintransfer       (),                                                                            //              (terminated)
		.av_writebyteenable     (),                                                                            //              (terminated)
		.av_lock                (),                                                                            //              (terminated)
		.av_chipselect          (),                                                                            //              (terminated)
		.av_clken               (),                                                                            //              (terminated)
		.uav_clken              (1'b0),                                                                        //              (terminated)
		.av_debugaccess         (),                                                                            //              (terminated)
		.av_outputenable        (),                                                                            //              (terminated)
		.uav_response           (),                                                                            //              (terminated)
		.av_response            (2'b00),                                                                       //              (terminated)
		.uav_writeresponsevalid (),                                                                            //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                         //              (terminated)
	);

endmodule
