// system_acl_iface_em_pc_0_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module system_acl_iface_em_pc_0_mm_interconnect_0 (
		input  wire        avl_clk_out_clk_clk,                                 //                               avl_clk_out_clk.clk
		input  wire        bridge_0_reset_reset_bridge_in_reset_reset,          //          bridge_0_reset_reset_bridge_in_reset.reset
		input  wire        em_pc_core_0_reset_sink_reset_bridge_in_reset_reset, // em_pc_core_0_reset_sink_reset_bridge_in_reset.reset
		input  wire [13:0] bridge_0_m0_address,                                 //                                   bridge_0_m0.address
		output wire        bridge_0_m0_waitrequest,                             //                                              .waitrequest
		input  wire [0:0]  bridge_0_m0_burstcount,                              //                                              .burstcount
		input  wire [3:0]  bridge_0_m0_byteenable,                              //                                              .byteenable
		input  wire        bridge_0_m0_read,                                    //                                              .read
		output wire [31:0] bridge_0_m0_readdata,                                //                                              .readdata
		output wire        bridge_0_m0_readdatavalid,                           //                                              .readdatavalid
		input  wire        bridge_0_m0_write,                                   //                                              .write
		input  wire [31:0] bridge_0_m0_writedata,                               //                                              .writedata
		input  wire        bridge_0_m0_debugaccess,                             //                                              .debugaccess
		output wire [11:0] em_pc_core_0_csr_address,                            //                              em_pc_core_0_csr.address
		output wire        em_pc_core_0_csr_write,                              //                                              .write
		output wire        em_pc_core_0_csr_read,                               //                                              .read
		input  wire [31:0] em_pc_core_0_csr_readdata,                           //                                              .readdata
		output wire [31:0] em_pc_core_0_csr_writedata,                          //                                              .writedata
		output wire [3:0]  em_pc_core_0_csr_byteenable,                         //                                              .byteenable
		input  wire        em_pc_core_0_csr_readdatavalid,                      //                                              .readdatavalid
		input  wire        em_pc_core_0_csr_waitrequest                         //                                              .waitrequest
	);

	wire         bridge_0_m0_translator_avalon_universal_master_0_waitrequest;   // em_pc_core_0_csr_translator:uav_waitrequest -> bridge_0_m0_translator:uav_waitrequest
	wire  [31:0] bridge_0_m0_translator_avalon_universal_master_0_readdata;      // em_pc_core_0_csr_translator:uav_readdata -> bridge_0_m0_translator:uav_readdata
	wire         bridge_0_m0_translator_avalon_universal_master_0_debugaccess;   // bridge_0_m0_translator:uav_debugaccess -> em_pc_core_0_csr_translator:uav_debugaccess
	wire  [13:0] bridge_0_m0_translator_avalon_universal_master_0_address;       // bridge_0_m0_translator:uav_address -> em_pc_core_0_csr_translator:uav_address
	wire         bridge_0_m0_translator_avalon_universal_master_0_read;          // bridge_0_m0_translator:uav_read -> em_pc_core_0_csr_translator:uav_read
	wire   [3:0] bridge_0_m0_translator_avalon_universal_master_0_byteenable;    // bridge_0_m0_translator:uav_byteenable -> em_pc_core_0_csr_translator:uav_byteenable
	wire         bridge_0_m0_translator_avalon_universal_master_0_readdatavalid; // em_pc_core_0_csr_translator:uav_readdatavalid -> bridge_0_m0_translator:uav_readdatavalid
	wire         bridge_0_m0_translator_avalon_universal_master_0_lock;          // bridge_0_m0_translator:uav_lock -> em_pc_core_0_csr_translator:uav_lock
	wire         bridge_0_m0_translator_avalon_universal_master_0_write;         // bridge_0_m0_translator:uav_write -> em_pc_core_0_csr_translator:uav_write
	wire  [31:0] bridge_0_m0_translator_avalon_universal_master_0_writedata;     // bridge_0_m0_translator:uav_writedata -> em_pc_core_0_csr_translator:uav_writedata
	wire   [2:0] bridge_0_m0_translator_avalon_universal_master_0_burstcount;    // bridge_0_m0_translator:uav_burstcount -> em_pc_core_0_csr_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (14),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (14),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) bridge_0_m0_translator (
		.clk                    (avl_clk_out_clk_clk),                                            //                       clk.clk
		.reset                  (bridge_0_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (bridge_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (bridge_0_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (bridge_0_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (bridge_0_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (bridge_0_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (bridge_0_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (bridge_0_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (bridge_0_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (bridge_0_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (bridge_0_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (bridge_0_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (bridge_0_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (bridge_0_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (bridge_0_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (bridge_0_m0_byteenable),                                         //                          .byteenable
		.av_read                (bridge_0_m0_read),                                               //                          .read
		.av_readdata            (bridge_0_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (bridge_0_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (bridge_0_m0_write),                                              //                          .write
		.av_writedata           (bridge_0_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (bridge_0_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                           //               (terminated)
		.av_begintransfer       (1'b0),                                                           //               (terminated)
		.av_chipselect          (1'b0),                                                           //               (terminated)
		.av_lock                (1'b0),                                                           //               (terminated)
		.uav_clken              (),                                                               //               (terminated)
		.av_clken               (1'b1),                                                           //               (terminated)
		.uav_response           (2'b00),                                                          //               (terminated)
		.av_response            (),                                                               //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                           //               (terminated)
		.av_writeresponsevalid  ()                                                                //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (12),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (14),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) em_pc_core_0_csr_translator (
		.clk                    (avl_clk_out_clk_clk),                                            //                      clk.clk
		.reset                  (bridge_0_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (bridge_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (bridge_0_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (bridge_0_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (bridge_0_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (bridge_0_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (bridge_0_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (bridge_0_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (bridge_0_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (bridge_0_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (bridge_0_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (bridge_0_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (em_pc_core_0_csr_address),                                       //      avalon_anti_slave_0.address
		.av_write               (em_pc_core_0_csr_write),                                         //                         .write
		.av_read                (em_pc_core_0_csr_read),                                          //                         .read
		.av_readdata            (em_pc_core_0_csr_readdata),                                      //                         .readdata
		.av_writedata           (em_pc_core_0_csr_writedata),                                     //                         .writedata
		.av_byteenable          (em_pc_core_0_csr_byteenable),                                    //                         .byteenable
		.av_readdatavalid       (em_pc_core_0_csr_readdatavalid),                                 //                         .readdatavalid
		.av_waitrequest         (em_pc_core_0_csr_waitrequest),                                   //                         .waitrequest
		.av_begintransfer       (),                                                               //              (terminated)
		.av_beginbursttransfer  (),                                                               //              (terminated)
		.av_burstcount          (),                                                               //              (terminated)
		.av_writebyteenable     (),                                                               //              (terminated)
		.av_lock                (),                                                               //              (terminated)
		.av_chipselect          (),                                                               //              (terminated)
		.av_clken               (),                                                               //              (terminated)
		.uav_clken              (1'b0),                                                           //              (terminated)
		.av_debugaccess         (),                                                               //              (terminated)
		.av_outputenable        (),                                                               //              (terminated)
		.uav_response           (),                                                               //              (terminated)
		.av_response            (2'b00),                                                          //              (terminated)
		.uav_writeresponsevalid (),                                                               //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                            //              (terminated)
	);

endmodule
