// system_acl_iface_mm_interconnect_8.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module system_acl_iface_mm_interconnect_8 (
		input  wire         pcie_coreclkout_clk,                                        //                                      pcie_coreclkout.clk
		input  wire         pcie_Rxm_BAR0_translator_reset_reset_bridge_in_reset_reset, // pcie_Rxm_BAR0_translator_reset_reset_bridge_in_reset.reset
		input  wire         pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset,     //     pipe_stage_host_ctrl_reset_reset_bridge_in_reset.reset
		input  wire [31:0]  pcie_Rxm_BAR0_address,                                      //                                        pcie_Rxm_BAR0.address
		output wire         pcie_Rxm_BAR0_waitrequest,                                  //                                                     .waitrequest
		input  wire [5:0]   pcie_Rxm_BAR0_burstcount,                                   //                                                     .burstcount
		input  wire [15:0]  pcie_Rxm_BAR0_byteenable,                                   //                                                     .byteenable
		input  wire         pcie_Rxm_BAR0_read,                                         //                                                     .read
		output wire [127:0] pcie_Rxm_BAR0_readdata,                                     //                                                     .readdata
		output wire         pcie_Rxm_BAR0_readdatavalid,                                //                                                     .readdatavalid
		input  wire         pcie_Rxm_BAR0_write,                                        //                                                     .write
		input  wire [127:0] pcie_Rxm_BAR0_writedata,                                    //                                                     .writedata
		output wire [17:0]  pipe_stage_host_ctrl_s0_address,                            //                              pipe_stage_host_ctrl_s0.address
		output wire         pipe_stage_host_ctrl_s0_write,                              //                                                     .write
		output wire         pipe_stage_host_ctrl_s0_read,                               //                                                     .read
		input  wire [31:0]  pipe_stage_host_ctrl_s0_readdata,                           //                                                     .readdata
		output wire [31:0]  pipe_stage_host_ctrl_s0_writedata,                          //                                                     .writedata
		output wire [0:0]   pipe_stage_host_ctrl_s0_burstcount,                         //                                                     .burstcount
		output wire [3:0]   pipe_stage_host_ctrl_s0_byteenable,                         //                                                     .byteenable
		input  wire         pipe_stage_host_ctrl_s0_readdatavalid,                      //                                                     .readdatavalid
		input  wire         pipe_stage_host_ctrl_s0_waitrequest,                        //                                                     .waitrequest
		output wire         pipe_stage_host_ctrl_s0_debugaccess                         //                                                     .debugaccess
	);

	wire          pcie_rxm_bar0_translator_avalon_universal_master_0_waitrequest;   // pcie_Rxm_BAR0_agent:av_waitrequest -> pcie_Rxm_BAR0_translator:uav_waitrequest
	wire  [127:0] pcie_rxm_bar0_translator_avalon_universal_master_0_readdata;      // pcie_Rxm_BAR0_agent:av_readdata -> pcie_Rxm_BAR0_translator:uav_readdata
	wire          pcie_rxm_bar0_translator_avalon_universal_master_0_debugaccess;   // pcie_Rxm_BAR0_translator:uav_debugaccess -> pcie_Rxm_BAR0_agent:av_debugaccess
	wire   [31:0] pcie_rxm_bar0_translator_avalon_universal_master_0_address;       // pcie_Rxm_BAR0_translator:uav_address -> pcie_Rxm_BAR0_agent:av_address
	wire          pcie_rxm_bar0_translator_avalon_universal_master_0_read;          // pcie_Rxm_BAR0_translator:uav_read -> pcie_Rxm_BAR0_agent:av_read
	wire   [15:0] pcie_rxm_bar0_translator_avalon_universal_master_0_byteenable;    // pcie_Rxm_BAR0_translator:uav_byteenable -> pcie_Rxm_BAR0_agent:av_byteenable
	wire          pcie_rxm_bar0_translator_avalon_universal_master_0_readdatavalid; // pcie_Rxm_BAR0_agent:av_readdatavalid -> pcie_Rxm_BAR0_translator:uav_readdatavalid
	wire          pcie_rxm_bar0_translator_avalon_universal_master_0_lock;          // pcie_Rxm_BAR0_translator:uav_lock -> pcie_Rxm_BAR0_agent:av_lock
	wire          pcie_rxm_bar0_translator_avalon_universal_master_0_write;         // pcie_Rxm_BAR0_translator:uav_write -> pcie_Rxm_BAR0_agent:av_write
	wire  [127:0] pcie_rxm_bar0_translator_avalon_universal_master_0_writedata;     // pcie_Rxm_BAR0_translator:uav_writedata -> pcie_Rxm_BAR0_agent:av_writedata
	wire    [9:0] pcie_rxm_bar0_translator_avalon_universal_master_0_burstcount;    // pcie_Rxm_BAR0_translator:uav_burstcount -> pcie_Rxm_BAR0_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                // rsp_mux:src_valid -> pcie_Rxm_BAR0_agent:rp_valid
	wire  [216:0] rsp_mux_src_data;                                                 // rsp_mux:src_data -> pcie_Rxm_BAR0_agent:rp_data
	wire          rsp_mux_src_ready;                                                // pcie_Rxm_BAR0_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                              // rsp_mux:src_channel -> pcie_Rxm_BAR0_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                        // rsp_mux:src_startofpacket -> pcie_Rxm_BAR0_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                          // rsp_mux:src_endofpacket -> pcie_Rxm_BAR0_agent:rp_endofpacket
	wire   [31:0] pipe_stage_host_ctrl_s0_agent_m0_readdata;                        // pipe_stage_host_ctrl_s0_translator:uav_readdata -> pipe_stage_host_ctrl_s0_agent:m0_readdata
	wire          pipe_stage_host_ctrl_s0_agent_m0_waitrequest;                     // pipe_stage_host_ctrl_s0_translator:uav_waitrequest -> pipe_stage_host_ctrl_s0_agent:m0_waitrequest
	wire          pipe_stage_host_ctrl_s0_agent_m0_debugaccess;                     // pipe_stage_host_ctrl_s0_agent:m0_debugaccess -> pipe_stage_host_ctrl_s0_translator:uav_debugaccess
	wire   [31:0] pipe_stage_host_ctrl_s0_agent_m0_address;                         // pipe_stage_host_ctrl_s0_agent:m0_address -> pipe_stage_host_ctrl_s0_translator:uav_address
	wire    [3:0] pipe_stage_host_ctrl_s0_agent_m0_byteenable;                      // pipe_stage_host_ctrl_s0_agent:m0_byteenable -> pipe_stage_host_ctrl_s0_translator:uav_byteenable
	wire          pipe_stage_host_ctrl_s0_agent_m0_read;                            // pipe_stage_host_ctrl_s0_agent:m0_read -> pipe_stage_host_ctrl_s0_translator:uav_read
	wire          pipe_stage_host_ctrl_s0_agent_m0_readdatavalid;                   // pipe_stage_host_ctrl_s0_translator:uav_readdatavalid -> pipe_stage_host_ctrl_s0_agent:m0_readdatavalid
	wire          pipe_stage_host_ctrl_s0_agent_m0_lock;                            // pipe_stage_host_ctrl_s0_agent:m0_lock -> pipe_stage_host_ctrl_s0_translator:uav_lock
	wire   [31:0] pipe_stage_host_ctrl_s0_agent_m0_writedata;                       // pipe_stage_host_ctrl_s0_agent:m0_writedata -> pipe_stage_host_ctrl_s0_translator:uav_writedata
	wire          pipe_stage_host_ctrl_s0_agent_m0_write;                           // pipe_stage_host_ctrl_s0_agent:m0_write -> pipe_stage_host_ctrl_s0_translator:uav_write
	wire    [2:0] pipe_stage_host_ctrl_s0_agent_m0_burstcount;                      // pipe_stage_host_ctrl_s0_agent:m0_burstcount -> pipe_stage_host_ctrl_s0_translator:uav_burstcount
	wire          pipe_stage_host_ctrl_s0_agent_rf_source_valid;                    // pipe_stage_host_ctrl_s0_agent:rf_source_valid -> pipe_stage_host_ctrl_s0_agent_rsp_fifo:in_valid
	wire  [109:0] pipe_stage_host_ctrl_s0_agent_rf_source_data;                     // pipe_stage_host_ctrl_s0_agent:rf_source_data -> pipe_stage_host_ctrl_s0_agent_rsp_fifo:in_data
	wire          pipe_stage_host_ctrl_s0_agent_rf_source_ready;                    // pipe_stage_host_ctrl_s0_agent_rsp_fifo:in_ready -> pipe_stage_host_ctrl_s0_agent:rf_source_ready
	wire          pipe_stage_host_ctrl_s0_agent_rf_source_startofpacket;            // pipe_stage_host_ctrl_s0_agent:rf_source_startofpacket -> pipe_stage_host_ctrl_s0_agent_rsp_fifo:in_startofpacket
	wire          pipe_stage_host_ctrl_s0_agent_rf_source_endofpacket;              // pipe_stage_host_ctrl_s0_agent:rf_source_endofpacket -> pipe_stage_host_ctrl_s0_agent_rsp_fifo:in_endofpacket
	wire          pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_valid;                 // pipe_stage_host_ctrl_s0_agent_rsp_fifo:out_valid -> pipe_stage_host_ctrl_s0_agent:rf_sink_valid
	wire  [109:0] pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_data;                  // pipe_stage_host_ctrl_s0_agent_rsp_fifo:out_data -> pipe_stage_host_ctrl_s0_agent:rf_sink_data
	wire          pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_ready;                 // pipe_stage_host_ctrl_s0_agent:rf_sink_ready -> pipe_stage_host_ctrl_s0_agent_rsp_fifo:out_ready
	wire          pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_startofpacket;         // pipe_stage_host_ctrl_s0_agent_rsp_fifo:out_startofpacket -> pipe_stage_host_ctrl_s0_agent:rf_sink_startofpacket
	wire          pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_endofpacket;           // pipe_stage_host_ctrl_s0_agent_rsp_fifo:out_endofpacket -> pipe_stage_host_ctrl_s0_agent:rf_sink_endofpacket
	wire          pcie_rxm_bar0_agent_cp_valid;                                     // pcie_Rxm_BAR0_agent:cp_valid -> router:sink_valid
	wire  [216:0] pcie_rxm_bar0_agent_cp_data;                                      // pcie_Rxm_BAR0_agent:cp_data -> router:sink_data
	wire          pcie_rxm_bar0_agent_cp_ready;                                     // router:sink_ready -> pcie_Rxm_BAR0_agent:cp_ready
	wire          pcie_rxm_bar0_agent_cp_startofpacket;                             // pcie_Rxm_BAR0_agent:cp_startofpacket -> router:sink_startofpacket
	wire          pcie_rxm_bar0_agent_cp_endofpacket;                               // pcie_Rxm_BAR0_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                 // router:src_valid -> cmd_demux:sink_valid
	wire  [216:0] router_src_data;                                                  // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                 // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                               // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                         // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                           // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          pipe_stage_host_ctrl_s0_agent_rp_valid;                           // pipe_stage_host_ctrl_s0_agent:rp_valid -> router_001:sink_valid
	wire  [108:0] pipe_stage_host_ctrl_s0_agent_rp_data;                            // pipe_stage_host_ctrl_s0_agent:rp_data -> router_001:sink_data
	wire          pipe_stage_host_ctrl_s0_agent_rp_ready;                           // router_001:sink_ready -> pipe_stage_host_ctrl_s0_agent:rp_ready
	wire          pipe_stage_host_ctrl_s0_agent_rp_startofpacket;                   // pipe_stage_host_ctrl_s0_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          pipe_stage_host_ctrl_s0_agent_rp_endofpacket;                     // pipe_stage_host_ctrl_s0_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          pipe_stage_host_ctrl_s0_burst_adapter_source0_valid;              // pipe_stage_host_ctrl_s0_burst_adapter:source0_valid -> pipe_stage_host_ctrl_s0_agent:cp_valid
	wire  [108:0] pipe_stage_host_ctrl_s0_burst_adapter_source0_data;               // pipe_stage_host_ctrl_s0_burst_adapter:source0_data -> pipe_stage_host_ctrl_s0_agent:cp_data
	wire          pipe_stage_host_ctrl_s0_burst_adapter_source0_ready;              // pipe_stage_host_ctrl_s0_agent:cp_ready -> pipe_stage_host_ctrl_s0_burst_adapter:source0_ready
	wire    [0:0] pipe_stage_host_ctrl_s0_burst_adapter_source0_channel;            // pipe_stage_host_ctrl_s0_burst_adapter:source0_channel -> pipe_stage_host_ctrl_s0_agent:cp_channel
	wire          pipe_stage_host_ctrl_s0_burst_adapter_source0_startofpacket;      // pipe_stage_host_ctrl_s0_burst_adapter:source0_startofpacket -> pipe_stage_host_ctrl_s0_agent:cp_startofpacket
	wire          pipe_stage_host_ctrl_s0_burst_adapter_source0_endofpacket;        // pipe_stage_host_ctrl_s0_burst_adapter:source0_endofpacket -> pipe_stage_host_ctrl_s0_agent:cp_endofpacket
	wire          cmd_demux_src0_valid;                                             // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [216:0] cmd_demux_src0_data;                                              // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                             // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                           // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                     // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                       // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                             // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [216:0] rsp_demux_src0_data;                                              // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                             // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                           // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                     // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                       // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          router_001_src_valid;                                             // router_001:src_valid -> pipe_stage_host_ctrl_s0_rsp_width_adapter:in_valid
	wire  [108:0] router_001_src_data;                                              // router_001:src_data -> pipe_stage_host_ctrl_s0_rsp_width_adapter:in_data
	wire          router_001_src_ready;                                             // pipe_stage_host_ctrl_s0_rsp_width_adapter:in_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                           // router_001:src_channel -> pipe_stage_host_ctrl_s0_rsp_width_adapter:in_channel
	wire          router_001_src_startofpacket;                                     // router_001:src_startofpacket -> pipe_stage_host_ctrl_s0_rsp_width_adapter:in_startofpacket
	wire          router_001_src_endofpacket;                                       // router_001:src_endofpacket -> pipe_stage_host_ctrl_s0_rsp_width_adapter:in_endofpacket
	wire          pipe_stage_host_ctrl_s0_rsp_width_adapter_src_valid;              // pipe_stage_host_ctrl_s0_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire  [216:0] pipe_stage_host_ctrl_s0_rsp_width_adapter_src_data;               // pipe_stage_host_ctrl_s0_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire          pipe_stage_host_ctrl_s0_rsp_width_adapter_src_ready;              // rsp_demux:sink_ready -> pipe_stage_host_ctrl_s0_rsp_width_adapter:out_ready
	wire    [0:0] pipe_stage_host_ctrl_s0_rsp_width_adapter_src_channel;            // pipe_stage_host_ctrl_s0_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire          pipe_stage_host_ctrl_s0_rsp_width_adapter_src_startofpacket;      // pipe_stage_host_ctrl_s0_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire          pipe_stage_host_ctrl_s0_rsp_width_adapter_src_endofpacket;        // pipe_stage_host_ctrl_s0_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_mux_src_valid;                                                // cmd_mux:src_valid -> pipe_stage_host_ctrl_s0_cmd_width_adapter:in_valid
	wire  [216:0] cmd_mux_src_data;                                                 // cmd_mux:src_data -> pipe_stage_host_ctrl_s0_cmd_width_adapter:in_data
	wire          cmd_mux_src_ready;                                                // pipe_stage_host_ctrl_s0_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                              // cmd_mux:src_channel -> pipe_stage_host_ctrl_s0_cmd_width_adapter:in_channel
	wire          cmd_mux_src_startofpacket;                                        // cmd_mux:src_startofpacket -> pipe_stage_host_ctrl_s0_cmd_width_adapter:in_startofpacket
	wire          cmd_mux_src_endofpacket;                                          // cmd_mux:src_endofpacket -> pipe_stage_host_ctrl_s0_cmd_width_adapter:in_endofpacket
	wire          pipe_stage_host_ctrl_s0_cmd_width_adapter_src_valid;              // pipe_stage_host_ctrl_s0_cmd_width_adapter:out_valid -> pipe_stage_host_ctrl_s0_burst_adapter:sink0_valid
	wire  [108:0] pipe_stage_host_ctrl_s0_cmd_width_adapter_src_data;               // pipe_stage_host_ctrl_s0_cmd_width_adapter:out_data -> pipe_stage_host_ctrl_s0_burst_adapter:sink0_data
	wire          pipe_stage_host_ctrl_s0_cmd_width_adapter_src_ready;              // pipe_stage_host_ctrl_s0_burst_adapter:sink0_ready -> pipe_stage_host_ctrl_s0_cmd_width_adapter:out_ready
	wire    [0:0] pipe_stage_host_ctrl_s0_cmd_width_adapter_src_channel;            // pipe_stage_host_ctrl_s0_cmd_width_adapter:out_channel -> pipe_stage_host_ctrl_s0_burst_adapter:sink0_channel
	wire          pipe_stage_host_ctrl_s0_cmd_width_adapter_src_startofpacket;      // pipe_stage_host_ctrl_s0_cmd_width_adapter:out_startofpacket -> pipe_stage_host_ctrl_s0_burst_adapter:sink0_startofpacket
	wire          pipe_stage_host_ctrl_s0_cmd_width_adapter_src_endofpacket;        // pipe_stage_host_ctrl_s0_cmd_width_adapter:out_endofpacket -> pipe_stage_host_ctrl_s0_burst_adapter:sink0_endofpacket
	wire          pipe_stage_host_ctrl_s0_agent_rdata_fifo_src_valid;               // pipe_stage_host_ctrl_s0_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire   [33:0] pipe_stage_host_ctrl_s0_agent_rdata_fifo_src_data;                // pipe_stage_host_ctrl_s0_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire          pipe_stage_host_ctrl_s0_agent_rdata_fifo_src_ready;               // avalon_st_adapter:in_0_ready -> pipe_stage_host_ctrl_s0_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_out_0_valid;                                    // avalon_st_adapter:out_0_valid -> pipe_stage_host_ctrl_s0_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_out_0_data;                                     // avalon_st_adapter:out_0_data -> pipe_stage_host_ctrl_s0_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                    // pipe_stage_host_ctrl_s0_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                    // avalon_st_adapter:out_0_error -> pipe_stage_host_ctrl_s0_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (128),
		.AV_BURSTCOUNT_W             (6),
		.AV_BYTEENABLE_W             (16),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (10),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (16),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) pcie_rxm_bar0_translator (
		.clk                    (pcie_coreclkout_clk),                                              //                       clk.clk
		.reset                  (pcie_Rxm_BAR0_translator_reset_reset_bridge_in_reset_reset),       //                     reset.reset
		.uav_address            (pcie_rxm_bar0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (pcie_rxm_bar0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (pcie_rxm_bar0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (pcie_rxm_bar0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (pcie_rxm_bar0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (pcie_rxm_bar0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (pcie_rxm_bar0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (pcie_rxm_bar0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (pcie_rxm_bar0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (pcie_rxm_bar0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (pcie_rxm_bar0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (pcie_Rxm_BAR0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (pcie_Rxm_BAR0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (pcie_Rxm_BAR0_burstcount),                                         //                          .burstcount
		.av_byteenable          (pcie_Rxm_BAR0_byteenable),                                         //                          .byteenable
		.av_read                (pcie_Rxm_BAR0_read),                                               //                          .read
		.av_readdata            (pcie_Rxm_BAR0_readdata),                                           //                          .readdata
		.av_readdatavalid       (pcie_Rxm_BAR0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (pcie_Rxm_BAR0_write),                                              //                          .write
		.av_writedata           (pcie_Rxm_BAR0_writedata),                                          //                          .writedata
		.av_beginbursttransfer  (1'b0),                                                             //               (terminated)
		.av_begintransfer       (1'b0),                                                             //               (terminated)
		.av_chipselect          (1'b0),                                                             //               (terminated)
		.av_lock                (1'b0),                                                             //               (terminated)
		.av_debugaccess         (1'b0),                                                             //               (terminated)
		.uav_clken              (),                                                                 //               (terminated)
		.av_clken               (1'b1),                                                             //               (terminated)
		.uav_response           (2'b00),                                                            //               (terminated)
		.av_response            (),                                                                 //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                             //               (terminated)
		.av_writeresponsevalid  ()                                                                  //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (18),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) pipe_stage_host_ctrl_s0_translator (
		.clk                    (pcie_coreclkout_clk),                                    //                      clk.clk
		.reset                  (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (pipe_stage_host_ctrl_s0_agent_m0_address),               // avalon_universal_slave_0.address
		.uav_burstcount         (pipe_stage_host_ctrl_s0_agent_m0_burstcount),            //                         .burstcount
		.uav_read               (pipe_stage_host_ctrl_s0_agent_m0_read),                  //                         .read
		.uav_write              (pipe_stage_host_ctrl_s0_agent_m0_write),                 //                         .write
		.uav_waitrequest        (pipe_stage_host_ctrl_s0_agent_m0_waitrequest),           //                         .waitrequest
		.uav_readdatavalid      (pipe_stage_host_ctrl_s0_agent_m0_readdatavalid),         //                         .readdatavalid
		.uav_byteenable         (pipe_stage_host_ctrl_s0_agent_m0_byteenable),            //                         .byteenable
		.uav_readdata           (pipe_stage_host_ctrl_s0_agent_m0_readdata),              //                         .readdata
		.uav_writedata          (pipe_stage_host_ctrl_s0_agent_m0_writedata),             //                         .writedata
		.uav_lock               (pipe_stage_host_ctrl_s0_agent_m0_lock),                  //                         .lock
		.uav_debugaccess        (pipe_stage_host_ctrl_s0_agent_m0_debugaccess),           //                         .debugaccess
		.av_address             (pipe_stage_host_ctrl_s0_address),                        //      avalon_anti_slave_0.address
		.av_write               (pipe_stage_host_ctrl_s0_write),                          //                         .write
		.av_read                (pipe_stage_host_ctrl_s0_read),                           //                         .read
		.av_readdata            (pipe_stage_host_ctrl_s0_readdata),                       //                         .readdata
		.av_writedata           (pipe_stage_host_ctrl_s0_writedata),                      //                         .writedata
		.av_burstcount          (pipe_stage_host_ctrl_s0_burstcount),                     //                         .burstcount
		.av_byteenable          (pipe_stage_host_ctrl_s0_byteenable),                     //                         .byteenable
		.av_readdatavalid       (pipe_stage_host_ctrl_s0_readdatavalid),                  //                         .readdatavalid
		.av_waitrequest         (pipe_stage_host_ctrl_s0_waitrequest),                    //                         .waitrequest
		.av_debugaccess         (pipe_stage_host_ctrl_s0_debugaccess),                    //                         .debugaccess
		.av_begintransfer       (),                                                       //              (terminated)
		.av_beginbursttransfer  (),                                                       //              (terminated)
		.av_writebyteenable     (),                                                       //              (terminated)
		.av_lock                (),                                                       //              (terminated)
		.av_chipselect          (),                                                       //              (terminated)
		.av_clken               (),                                                       //              (terminated)
		.uav_clken              (1'b0),                                                   //              (terminated)
		.av_outputenable        (),                                                       //              (terminated)
		.uav_response           (),                                                       //              (terminated)
		.av_response            (2'b00),                                                  //              (terminated)
		.uav_writeresponsevalid (),                                                       //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                    //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (216),
		.PKT_ORI_BURST_SIZE_L      (214),
		.PKT_RESPONSE_STATUS_H     (213),
		.PKT_RESPONSE_STATUS_L     (212),
		.PKT_QOS_H                 (201),
		.PKT_QOS_L                 (201),
		.PKT_DATA_SIDEBAND_H       (199),
		.PKT_DATA_SIDEBAND_L       (199),
		.PKT_ADDR_SIDEBAND_H       (198),
		.PKT_ADDR_SIDEBAND_L       (198),
		.PKT_BURST_TYPE_H          (197),
		.PKT_BURST_TYPE_L          (196),
		.PKT_CACHE_H               (211),
		.PKT_CACHE_L               (208),
		.PKT_THREAD_ID_H           (204),
		.PKT_THREAD_ID_L           (204),
		.PKT_BURST_SIZE_H          (195),
		.PKT_BURST_SIZE_L          (193),
		.PKT_TRANS_EXCLUSIVE       (181),
		.PKT_TRANS_LOCK            (180),
		.PKT_BEGIN_BURST           (200),
		.PKT_PROTECTION_H          (207),
		.PKT_PROTECTION_L          (205),
		.PKT_BURSTWRAP_H           (192),
		.PKT_BURSTWRAP_L           (192),
		.PKT_BYTE_CNT_H            (191),
		.PKT_BYTE_CNT_L            (182),
		.PKT_ADDR_H                (175),
		.PKT_ADDR_L                (144),
		.PKT_TRANS_COMPRESSED_READ (176),
		.PKT_TRANS_POSTED          (177),
		.PKT_TRANS_WRITE           (178),
		.PKT_TRANS_READ            (179),
		.PKT_DATA_H                (127),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_SRC_ID_H              (202),
		.PKT_SRC_ID_L              (202),
		.PKT_DEST_ID_H             (203),
		.PKT_DEST_ID_L             (203),
		.ST_DATA_W                 (217),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (10),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) pcie_rxm_bar0_agent (
		.clk                   (pcie_coreclkout_clk),                                              //       clk.clk
		.reset                 (pcie_Rxm_BAR0_translator_reset_reset_bridge_in_reset_reset),       // clk_reset.reset
		.av_address            (pcie_rxm_bar0_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (pcie_rxm_bar0_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (pcie_rxm_bar0_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (pcie_rxm_bar0_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (pcie_rxm_bar0_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (pcie_rxm_bar0_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (pcie_rxm_bar0_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (pcie_rxm_bar0_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (pcie_rxm_bar0_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (pcie_rxm_bar0_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (pcie_rxm_bar0_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (pcie_rxm_bar0_agent_cp_valid),                                     //        cp.valid
		.cp_data               (pcie_rxm_bar0_agent_cp_data),                                      //          .data
		.cp_startofpacket      (pcie_rxm_bar0_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (pcie_rxm_bar0_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (pcie_rxm_bar0_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                 //          .data
		.rp_channel            (rsp_mux_src_channel),                                              //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                        //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                          //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                //          .ready
		.av_response           (),                                                                 // (terminated)
		.av_writeresponsevalid ()                                                                  // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (108),
		.PKT_ORI_BURST_SIZE_L      (106),
		.PKT_RESPONSE_STATUS_H     (105),
		.PKT_RESPONSE_STATUS_L     (104),
		.PKT_BURST_SIZE_H          (87),
		.PKT_BURST_SIZE_L          (85),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (92),
		.PKT_PROTECTION_H          (99),
		.PKT_PROTECTION_L          (97),
		.PKT_BURSTWRAP_H           (84),
		.PKT_BURSTWRAP_L           (84),
		.PKT_BYTE_CNT_H            (83),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (94),
		.PKT_SRC_ID_L              (94),
		.PKT_DEST_ID_H             (95),
		.PKT_DEST_ID_L             (95),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (109),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (1),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) pipe_stage_host_ctrl_s0_agent (
		.clk                     (pcie_coreclkout_clk),                                         //             clk.clk
		.reset                   (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset),      //       clk_reset.reset
		.m0_address              (pipe_stage_host_ctrl_s0_agent_m0_address),                    //              m0.address
		.m0_burstcount           (pipe_stage_host_ctrl_s0_agent_m0_burstcount),                 //                .burstcount
		.m0_byteenable           (pipe_stage_host_ctrl_s0_agent_m0_byteenable),                 //                .byteenable
		.m0_debugaccess          (pipe_stage_host_ctrl_s0_agent_m0_debugaccess),                //                .debugaccess
		.m0_lock                 (pipe_stage_host_ctrl_s0_agent_m0_lock),                       //                .lock
		.m0_readdata             (pipe_stage_host_ctrl_s0_agent_m0_readdata),                   //                .readdata
		.m0_readdatavalid        (pipe_stage_host_ctrl_s0_agent_m0_readdatavalid),              //                .readdatavalid
		.m0_read                 (pipe_stage_host_ctrl_s0_agent_m0_read),                       //                .read
		.m0_waitrequest          (pipe_stage_host_ctrl_s0_agent_m0_waitrequest),                //                .waitrequest
		.m0_writedata            (pipe_stage_host_ctrl_s0_agent_m0_writedata),                  //                .writedata
		.m0_write                (pipe_stage_host_ctrl_s0_agent_m0_write),                      //                .write
		.rp_endofpacket          (pipe_stage_host_ctrl_s0_agent_rp_endofpacket),                //              rp.endofpacket
		.rp_ready                (pipe_stage_host_ctrl_s0_agent_rp_ready),                      //                .ready
		.rp_valid                (pipe_stage_host_ctrl_s0_agent_rp_valid),                      //                .valid
		.rp_data                 (pipe_stage_host_ctrl_s0_agent_rp_data),                       //                .data
		.rp_startofpacket        (pipe_stage_host_ctrl_s0_agent_rp_startofpacket),              //                .startofpacket
		.cp_ready                (pipe_stage_host_ctrl_s0_burst_adapter_source0_ready),         //              cp.ready
		.cp_valid                (pipe_stage_host_ctrl_s0_burst_adapter_source0_valid),         //                .valid
		.cp_data                 (pipe_stage_host_ctrl_s0_burst_adapter_source0_data),          //                .data
		.cp_startofpacket        (pipe_stage_host_ctrl_s0_burst_adapter_source0_startofpacket), //                .startofpacket
		.cp_endofpacket          (pipe_stage_host_ctrl_s0_burst_adapter_source0_endofpacket),   //                .endofpacket
		.cp_channel              (pipe_stage_host_ctrl_s0_burst_adapter_source0_channel),       //                .channel
		.rf_sink_ready           (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_ready),            //         rf_sink.ready
		.rf_sink_valid           (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_valid),            //                .valid
		.rf_sink_startofpacket   (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_startofpacket),    //                .startofpacket
		.rf_sink_endofpacket     (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_endofpacket),      //                .endofpacket
		.rf_sink_data            (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_data),             //                .data
		.rf_source_ready         (pipe_stage_host_ctrl_s0_agent_rf_source_ready),               //       rf_source.ready
		.rf_source_valid         (pipe_stage_host_ctrl_s0_agent_rf_source_valid),               //                .valid
		.rf_source_startofpacket (pipe_stage_host_ctrl_s0_agent_rf_source_startofpacket),       //                .startofpacket
		.rf_source_endofpacket   (pipe_stage_host_ctrl_s0_agent_rf_source_endofpacket),         //                .endofpacket
		.rf_source_data          (pipe_stage_host_ctrl_s0_agent_rf_source_data),                //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                               // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                               //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                                //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                               //                .error
		.rdata_fifo_src_ready    (pipe_stage_host_ctrl_s0_agent_rdata_fifo_src_ready),          //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (pipe_stage_host_ctrl_s0_agent_rdata_fifo_src_valid),          //                .valid
		.rdata_fifo_src_data     (pipe_stage_host_ctrl_s0_agent_rdata_fifo_src_data),           //                .data
		.m0_response             (2'b00),                                                       //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                         //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (110),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) pipe_stage_host_ctrl_s0_agent_rsp_fifo (
		.clk               (pcie_coreclkout_clk),                                      //       clk.clk
		.reset             (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset),   // clk_reset.reset
		.in_data           (pipe_stage_host_ctrl_s0_agent_rf_source_data),             //        in.data
		.in_valid          (pipe_stage_host_ctrl_s0_agent_rf_source_valid),            //          .valid
		.in_ready          (pipe_stage_host_ctrl_s0_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (pipe_stage_host_ctrl_s0_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (pipe_stage_host_ctrl_s0_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (pipe_stage_host_ctrl_s0_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                                    // (terminated)
		.csr_read          (1'b0),                                                     // (terminated)
		.csr_write         (1'b0),                                                     // (terminated)
		.csr_readdata      (),                                                         // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                     // (terminated)
		.almost_full_data  (),                                                         // (terminated)
		.almost_empty_data (),                                                         // (terminated)
		.in_empty          (1'b0),                                                     // (terminated)
		.out_empty         (),                                                         // (terminated)
		.in_error          (1'b0),                                                     // (terminated)
		.out_error         (),                                                         // (terminated)
		.in_channel        (1'b0),                                                     // (terminated)
		.out_channel       ()                                                          // (terminated)
	);

	system_acl_iface_mm_interconnect_8_router router (
		.sink_ready         (pcie_rxm_bar0_agent_cp_ready),                               //      sink.ready
		.sink_valid         (pcie_rxm_bar0_agent_cp_valid),                               //          .valid
		.sink_data          (pcie_rxm_bar0_agent_cp_data),                                //          .data
		.sink_startofpacket (pcie_rxm_bar0_agent_cp_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (pcie_rxm_bar0_agent_cp_endofpacket),                         //          .endofpacket
		.clk                (pcie_coreclkout_clk),                                        //       clk.clk
		.reset              (pcie_Rxm_BAR0_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                           //       src.ready
		.src_valid          (router_src_valid),                                           //          .valid
		.src_data           (router_src_data),                                            //          .data
		.src_channel        (router_src_channel),                                         //          .channel
		.src_startofpacket  (router_src_startofpacket),                                   //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                      //          .endofpacket
	);

	system_acl_iface_mm_interconnect_8_router_001 router_001 (
		.sink_ready         (pipe_stage_host_ctrl_s0_agent_rp_ready),                 //      sink.ready
		.sink_valid         (pipe_stage_host_ctrl_s0_agent_rp_valid),                 //          .valid
		.sink_data          (pipe_stage_host_ctrl_s0_agent_rp_data),                  //          .data
		.sink_startofpacket (pipe_stage_host_ctrl_s0_agent_rp_startofpacket),         //          .startofpacket
		.sink_endofpacket   (pipe_stage_host_ctrl_s0_agent_rp_endofpacket),           //          .endofpacket
		.clk                (pcie_coreclkout_clk),                                    //       clk.clk
		.reset              (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                   //       src.ready
		.src_valid          (router_001_src_valid),                                   //          .valid
		.src_data           (router_001_src_data),                                    //          .data
		.src_channel        (router_001_src_channel),                                 //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                           //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                              //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_BEGIN_BURST           (92),
		.PKT_BYTE_CNT_H            (83),
		.PKT_BYTE_CNT_L            (74),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_BURST_SIZE_H          (87),
		.PKT_BURST_SIZE_L          (85),
		.PKT_BURST_TYPE_H          (89),
		.PKT_BURST_TYPE_L          (88),
		.PKT_BURSTWRAP_H           (84),
		.PKT_BURSTWRAP_L           (84),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (109),
		.ST_CHANNEL_W              (1),
		.OUT_BYTE_CNT_H            (76),
		.OUT_BURSTWRAP_H           (84),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("13.1")
	) pipe_stage_host_ctrl_s0_burst_adapter (
		.clk                   (pcie_coreclkout_clk),                                         //       cr0.clk
		.reset                 (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset),      // cr0_reset.reset
		.sink0_valid           (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_valid),         //     sink0.valid
		.sink0_data            (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_data),          //          .data
		.sink0_channel         (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_channel),       //          .channel
		.sink0_startofpacket   (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.sink0_endofpacket     (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_endofpacket),   //          .endofpacket
		.sink0_ready           (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_ready),         //          .ready
		.source0_valid         (pipe_stage_host_ctrl_s0_burst_adapter_source0_valid),         //   source0.valid
		.source0_data          (pipe_stage_host_ctrl_s0_burst_adapter_source0_data),          //          .data
		.source0_channel       (pipe_stage_host_ctrl_s0_burst_adapter_source0_channel),       //          .channel
		.source0_startofpacket (pipe_stage_host_ctrl_s0_burst_adapter_source0_startofpacket), //          .startofpacket
		.source0_endofpacket   (pipe_stage_host_ctrl_s0_burst_adapter_source0_endofpacket),   //          .endofpacket
		.source0_ready         (pipe_stage_host_ctrl_s0_burst_adapter_source0_ready)          //          .ready
	);

	system_acl_iface_mm_interconnect_8_cmd_demux cmd_demux (
		.clk                (pcie_coreclkout_clk),                                        //       clk.clk
		.reset              (pcie_Rxm_BAR0_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                           //      sink.ready
		.sink_channel       (router_src_channel),                                         //          .channel
		.sink_data          (router_src_data),                                            //          .data
		.sink_startofpacket (router_src_startofpacket),                                   //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                     //          .endofpacket
		.sink_valid         (router_src_valid),                                           //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                       //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                       //          .valid
		.src0_data          (cmd_demux_src0_data),                                        //          .data
		.src0_channel       (cmd_demux_src0_channel),                                     //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                               //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                  //          .endofpacket
	);

	system_acl_iface_mm_interconnect_8_cmd_mux cmd_mux (
		.clk                 (pcie_coreclkout_clk),                                    //       clk.clk
		.reset               (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                      //       src.ready
		.src_valid           (cmd_mux_src_valid),                                      //          .valid
		.src_data            (cmd_mux_src_data),                                       //          .data
		.src_channel         (cmd_mux_src_channel),                                    //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                              //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                   //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                   //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                                 //          .channel
		.sink0_data          (cmd_demux_src0_data),                                    //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                           //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                              //          .endofpacket
	);

	system_acl_iface_mm_interconnect_8_cmd_demux rsp_demux (
		.clk                (pcie_coreclkout_clk),                                         //       clk.clk
		.reset              (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset),      // clk_reset.reset
		.sink_ready         (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_ready),         //      sink.ready
		.sink_channel       (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_channel),       //          .channel
		.sink_data          (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_data),          //          .data
		.sink_startofpacket (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.sink_endofpacket   (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_endofpacket),   //          .endofpacket
		.sink_valid         (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_valid),         //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                        //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                        //          .valid
		.src0_data          (rsp_demux_src0_data),                                         //          .data
		.src0_channel       (rsp_demux_src0_channel),                                      //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                                //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                                   //          .endofpacket
	);

	system_acl_iface_mm_interconnect_8_rsp_mux rsp_mux (
		.clk                 (pcie_coreclkout_clk),                                        //       clk.clk
		.reset               (pcie_Rxm_BAR0_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                          //       src.ready
		.src_valid           (rsp_mux_src_valid),                                          //          .valid
		.src_data            (rsp_mux_src_data),                                           //          .data
		.src_channel         (rsp_mux_src_channel),                                        //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                  //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                    //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                       //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                       //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                     //          .channel
		.sink0_data          (rsp_demux_src0_data),                                        //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                               //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                                  //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (67),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (83),
		.IN_PKT_BYTE_CNT_L             (74),
		.IN_PKT_TRANS_COMPRESSED_READ  (68),
		.IN_PKT_TRANS_WRITE            (70),
		.IN_PKT_BURSTWRAP_H            (84),
		.IN_PKT_BURSTWRAP_L            (84),
		.IN_PKT_BURST_SIZE_H           (87),
		.IN_PKT_BURST_SIZE_L           (85),
		.IN_PKT_RESPONSE_STATUS_H      (105),
		.IN_PKT_RESPONSE_STATUS_L      (104),
		.IN_PKT_TRANS_EXCLUSIVE        (73),
		.IN_PKT_BURST_TYPE_H           (89),
		.IN_PKT_BURST_TYPE_L           (88),
		.IN_PKT_ORI_BURST_SIZE_L       (106),
		.IN_PKT_ORI_BURST_SIZE_H       (108),
		.IN_ST_DATA_W                  (109),
		.OUT_PKT_ADDR_H                (175),
		.OUT_PKT_ADDR_L                (144),
		.OUT_PKT_DATA_H                (127),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (143),
		.OUT_PKT_BYTEEN_L              (128),
		.OUT_PKT_BYTE_CNT_H            (191),
		.OUT_PKT_BYTE_CNT_L            (182),
		.OUT_PKT_TRANS_COMPRESSED_READ (176),
		.OUT_PKT_BURST_SIZE_H          (195),
		.OUT_PKT_BURST_SIZE_L          (193),
		.OUT_PKT_RESPONSE_STATUS_H     (213),
		.OUT_PKT_RESPONSE_STATUS_L     (212),
		.OUT_PKT_TRANS_EXCLUSIVE       (181),
		.OUT_PKT_BURST_TYPE_H          (197),
		.OUT_PKT_BURST_TYPE_L          (196),
		.OUT_PKT_ORI_BURST_SIZE_L      (214),
		.OUT_PKT_ORI_BURST_SIZE_H      (216),
		.OUT_ST_DATA_W                 (217),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) pipe_stage_host_ctrl_s0_rsp_width_adapter (
		.clk                  (pcie_coreclkout_clk),                                         //       clk.clk
		.reset                (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset),      // clk_reset.reset
		.in_valid             (router_001_src_valid),                                        //      sink.valid
		.in_channel           (router_001_src_channel),                                      //          .channel
		.in_startofpacket     (router_001_src_startofpacket),                                //          .startofpacket
		.in_endofpacket       (router_001_src_endofpacket),                                  //          .endofpacket
		.in_ready             (router_001_src_ready),                                        //          .ready
		.in_data              (router_001_src_data),                                         //          .data
		.out_endofpacket      (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_data),          //          .data
		.out_channel          (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_channel),       //          .channel
		.out_valid            (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_valid),         //          .valid
		.out_ready            (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (pipe_stage_host_ctrl_s0_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                                       // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (175),
		.IN_PKT_ADDR_L                 (144),
		.IN_PKT_DATA_H                 (127),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (143),
		.IN_PKT_BYTEEN_L               (128),
		.IN_PKT_BYTE_CNT_H             (191),
		.IN_PKT_BYTE_CNT_L             (182),
		.IN_PKT_TRANS_COMPRESSED_READ  (176),
		.IN_PKT_TRANS_WRITE            (178),
		.IN_PKT_BURSTWRAP_H            (192),
		.IN_PKT_BURSTWRAP_L            (192),
		.IN_PKT_BURST_SIZE_H           (195),
		.IN_PKT_BURST_SIZE_L           (193),
		.IN_PKT_RESPONSE_STATUS_H      (213),
		.IN_PKT_RESPONSE_STATUS_L      (212),
		.IN_PKT_TRANS_EXCLUSIVE        (181),
		.IN_PKT_BURST_TYPE_H           (197),
		.IN_PKT_BURST_TYPE_L           (196),
		.IN_PKT_ORI_BURST_SIZE_L       (214),
		.IN_PKT_ORI_BURST_SIZE_H       (216),
		.IN_ST_DATA_W                  (217),
		.OUT_PKT_ADDR_H                (67),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (83),
		.OUT_PKT_BYTE_CNT_L            (74),
		.OUT_PKT_TRANS_COMPRESSED_READ (68),
		.OUT_PKT_BURST_SIZE_H          (87),
		.OUT_PKT_BURST_SIZE_L          (85),
		.OUT_PKT_RESPONSE_STATUS_H     (105),
		.OUT_PKT_RESPONSE_STATUS_L     (104),
		.OUT_PKT_TRANS_EXCLUSIVE       (73),
		.OUT_PKT_BURST_TYPE_H          (89),
		.OUT_PKT_BURST_TYPE_L          (88),
		.OUT_PKT_ORI_BURST_SIZE_L      (106),
		.OUT_PKT_ORI_BURST_SIZE_H      (108),
		.OUT_ST_DATA_W                 (109),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) pipe_stage_host_ctrl_s0_cmd_width_adapter (
		.clk                  (pcie_coreclkout_clk),                                         //       clk.clk
		.reset                (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset),      // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                                           //      sink.valid
		.in_channel           (cmd_mux_src_channel),                                         //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                                   //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                                     //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                                           //          .ready
		.in_data              (cmd_mux_src_data),                                            //          .data
		.out_endofpacket      (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_data),          //          .data
		.out_channel          (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_channel),       //          .channel
		.out_valid            (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_valid),         //          .valid
		.out_ready            (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (pipe_stage_host_ctrl_s0_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                                       // (terminated)
	);

	system_acl_iface_mm_interconnect_2_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (pcie_coreclkout_clk),                                    // in_clk_0.clk
		.in_rst_0_reset (pipe_stage_host_ctrl_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (pipe_stage_host_ctrl_s0_agent_rdata_fifo_src_data),      //     in_0.data
		.in_0_valid     (pipe_stage_host_ctrl_s0_agent_rdata_fifo_src_valid),     //         .valid
		.in_0_ready     (pipe_stage_host_ctrl_s0_agent_rdata_fifo_src_ready),     //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                           //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                          //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                          //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                           //         .error
	);

endmodule
